### ISSUE TITLE
Make/revive LIDMKtlDevice

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#104]
This will resolve issues with devices that are using a different interface than HID on Linux, e.g. the built-in keyboard and touchpad, and devices that use special drivers

**Comment by adcxyz** [comment]
@sensestage - is this still on your agenda?

**Comment by LFSaw** [comment]
closed due to unresponsiveness of initiator. Added to https://github.com/ModalityTeam/Modality-toolkit/projects/1
