### ISSUE TITLE
Matrix mixer

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#107]

**Comment by adcxyz** [comment]
is that a maxtrixmixer for controls?
if yes, see Quarks/Influx ;-)

**Comment by LFSaw** [comment]
@sensestage ?

**Comment by bhabbestad** [comment]
I wonder if this is jeffs use case, the porting of his matrix mixer for controlling ar+kr processing

b

29. mai 2015 kl. 21:03 skrev LFSaw <notifications@github.com>:

**Comment by LFSaw** [comment]
is the use case anywhere documented?

**Comment by adcxyz** [comment]
jeff? marije?

**Comment by LFSaw** [comment]
I'll close this because it is unclear what it means
