### ISSUE TITLE
Insert effects

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#108]

**Comment by LFSaw** [comment]
needs more description.

**Comment by adcxyz** [comment]
is this effects as porcessing of control messages, as in #72?

**Comment by LFSaw** [comment]
as there is no-one replying with further information, I close this issue as being too little explicit.

**Comment by bhabbestad** [comment]
Hmm, I wonder if this was connected to the idea of including "master FX chain", 

master fader, EQ, compression, limiting,

all of this is available in UnitLib - and I seem to remember that we discussed the option of
a "breaking out" . 

This sounds like a great opportunity for a modality island, no?

So question would be - what , if any , modification is needed to make this work out?

b.


21. juni 2015 kl. 10:17 skrev LFSaw <notifications@github.com>:

**Comment by adcxyz** [comment]
in the Jitlib archipelago, there is also a MasterFX class which handles this...
