### ISSUE TITLE
sysex communication with devices for particular modes (e.g. NanoKontrol2)

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#112]

**Comment by sensestage** [comment]
See also #111

**Comment by LFSaw** [comment]
from the nanoKONTROL2 desc:

``` 
// don't touch the following code: these are sysex messages found from the Korg NanoKontrol2 editor. 
```
this needs explanation, esp. about what that code does since sysex may also kill your controller's setup.

**Comment by LFSaw** [comment]
so I looked into the [linked overtone sources](https://github.com/overtone/overtone/blob/master/src/overtone/device/midi/nanoKONTROL2.clj) and found this explanation text:

> External led mode allows you to control each of the nanoKontrol2's leds independently to button presses. This gives you much more control over the device. To enable external led mode, we need to send send the magical sysex incantation to the nanoKontrol2 midi-out object nko (this was determined by recording the sysex messages that the official Korg Kontrol Editor sends to perform this task.)

We should _at least_ tell people what's going on with their controller and, IMHO, _give them a handle to revert the action_.

This sysex implementation is currently broken in the MKtl_refactor_2 branch and _prevents it from being merged_. I therefore declare this as a bug.

**Comment by adcxyz** [comment]
"This sysex implementation is currently broken in the MKtl_refactor_2 branch ( @adcxyz ? ) and prevents it from being merged. I therefore declare this as a bug."
sorry, no time yet to figure out how the sysex / sysrt MIDIFuncs should best be integrated, 
the building process of these has been massively refactored.
coming ASAP :-)

**Comment by sensestage** [comment]
These are not MIDIFuncs - this is sending out....

**Comment by sensestage** [comment]
I haven't found the reverse sysex messages yet online...

But agreed that we need the extra comment...
Or make initialisation messages optional, or have them to be needed to be executed explicitly.

**Comment by adcxyz** [comment]
They are now specialMessages with names, which seems safer. 
How should we provide a method to send specialMessages?
On OSC it would just be destination.sendMsg(...)
On MIDI is it always sysex messages ? 
On HID, is there anything like this ?

**Comment by adcxyz** [comment]
OK, on MIDIOut.help I cannot verify that sysex is working. 
Can someone test this please?
Thanks!

**Comment by adcxyz** [comment]
@sensestage: would be nice to have this done for 0.9.0
- any ideas how to fix this?

**Comment by sensestage** [comment]
I don't have a device that needs this (or at least none where the message
format if figured out); but Tijs should be able to test with his
NanoKontrol2.

On Fri, Oct 16, 2015 at 11:03 PM, Alberto de Campo <notifications@github.com
