### ISSUE TITLE
descs : better reflection of pages in hardware

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#123]
Hardware pages should be reflected better,
e.g. old NanoKontrol, buttons, sliders and knobs per page, so they can be grouped and displayed accordingly.

**Comment by adcxyz** [comment]
the new concept of splitting descs per MIDI-port can also be used for dealing hardware pages, first example being the qunexus presets AB, C, D. It actually seems very nice to have an MKtl for each page, and organize their modal functionality separately rather than together.

**Comment by LFSaw** [comment]
there's already a semantical way to mark on which page an element is located. AFAI remember, it was implemented by @woutersnoei for MKtlGUI.
A prominent use case is the [LaunchControl XL controller](https://github.com/ModalityTeam/Modality-toolkit/blob/master/Modality/MKtlDescriptions/novation-launchcontrol-xl.desc.scd) in which you can toggle between pages:

<img width="620" alt="screen shot 2015-09-02 at 10 04 35" src="https://cloud.githubusercontent.com/assets/75468/9625940/1a741178-515a-11e5-98b9-dd94ca00ecea.png">

**Comment by adcxyz** [comment]
I think pages are represent well now, both within single descs (nanokontrol), as well as per hardware page, as in QuNexus. closing with 3ccc819.
