### ISSUE TITLE
HID: impact on linux does not parse report descriptor right

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#127]
There seems to be a bug in parsing the report descriptor of the impact gamepad.
Not sure where it is yet... or when it broke...

**Comment by LFSaw** [comment]
this should be either reported on the webpage or fixed.

**Comment by adcxyz** [comment]
any news on this one?

**Comment by adcxyz** [comment]
@sensestage - is this issue worth keeping?

**Comment by adcxyz** [comment]
moving to sleeping beauties.
