### ISSUE TITLE
MKtl device description does not differenciate between separate MIDI ports in a single device

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#129]
````
(
device: "PCR", 
protocol: 'midi',
// ...
);
````
however, the device PCR contains two different devices (here, one is a generic MIDI port, the other one is the keyboard and various other elements).

**Comment by sensestage** [comment]
Do we have it in CPH?

**Comment by sensestage** [comment]
See also #21

**Comment by sensestage** [comment]
close via 889c316835409042feae318519786fed8f9d9c7b
