### ISSUE TITLE
What about PKtl?

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#135]
removed in ecbccb9

**Comment by sensestage** [comment]
An interesting approach in:
https://github.com/ModalityTeam/Modality-toolkit/compare/specsUpdate

**Comment by adcxyz** [comment]
currently MKtlElement has the pattern support below,
and Miguels asPattern method can be done simply with 
Pn(~elem, repeats: 5);
instead of requiring knowledge of a new special method as in:
~elem.asPattern(5);
```
	// pattern support
	embedInStream { |inval|
		this.value.embedInStream(inval);
		^inval
	}

	asStream {
		^Pfunc({ |inval| this.value }).asStream
	}
```

**Comment by LFSaw** [comment]
So in this light, I'll close this issue.
