### ISSUE TITLE
Automated generation of desc filename?

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#136]
When exploring a device, maybe give hints on how the description file should be named?

**Comment by adcxyz** [comment]
solved by using website doc page paths as filename.

**Comment by LFSaw** [comment]
closed with 27476ceb386b066b3a7c7300351f7ee6a27d24a1:

naming convention is given in https://github.com/ModalityTeam/Modality-toolkit/blob/master/Modality/HelpSource/Reference/MKtl_description_files.schelp:

The filename should be of the following format:
```<vendor>-<device_name>.desc.scd```
where

+ ```<vendor>``` is lower-case name of vendor with spaces replaced by ```-```
+ ```<device-name>``` is lower-case name of the device with spaces replaced by ```-```
