### ISSUE TITLE
MIDI learn

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#137]

**Comment by LFSaw** [comment]
there's an example for this in the cookbook: 
https://github.com/ModalityTeam/ModalityWorkshop/blob/master/cookbook/MIDI-learn/basic%20midiLearn.scd

look at it and decide if this is enough to close the issue.

**Comment by adcxyz** [comment]
updated example, is good enough for 0.9.0 - keeping issue for next release

**Comment by adcxyz** [comment]
moving to sleeping beauties.
