### ISSUE TITLE
MKtl.rebuildFrom should always reload spec, even if it has the same name.

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#160]
As we have given the method a scary enough name, it is useful if it always rebuilds the elements, as the description may have changed even when the name stays the same, e.g. when fixing it.

**Comment by sensestage** [comment]
I think this is fixed.

**Comment by LFSaw** [comment]
we should keep this open until @adcxyz merged the MKtl rewrite branch.

**Comment by adcxyz** [comment]
might work already, needs tests

**Comment by adcxyz** [comment]
already done and tested just now: 
- asks to close device if open, then rebuilds all elements from desc it has, 
or new one passed in.
