### ISSUE TITLE
Buttons of LogitecExtreme3DPro now counting from 0 ?

### ISSUE THREAD

**Issue by tapage** [ModalityTeam/Modality-toolkit#163]
So I tried to run the code I used at the Landmark concert but noticed
the mapping of my buttons didn't work... 
off by one
Semantically this makes no sense (the buttons are numbered on the device)
From a programming perspective it does make some sense...
Would it be possible to create several different groupings within a DeviceSpec
and be able to 'assign' which one to use? While typing this I'm already disagreeing
with myself (just complicates stuff a lot more...)
any thoughts?

**Comment by adcxyz** [comment]
I just tested this again with virtual LPD8 and extreme3dpro, 
and it was a problem in the desc file: 
```
  description: (
 	\kn: Event.newFrom( (1..8).collect{ |midiNum, i|
		// orig: key is a number, which in elementAt gets treated as an index
-		[ i+1, (\midiMsgType: \cc, \type: \knob, \midiChan: 0, \midiNum: midiNum, \spec: \midiCC, \ioType: \inout ) ]
		// fix: make the key number a symbol!
+		[ (i+1).asSymbol, (\midiMsgType: \cc, \type: \knob, \midiChan: 0, \midiNum: midiNum, \spec: \midiCC, \ioType: \inout ) ]
 	}.flatten ),

// then these tests work consistently again: 
l = MKtl(\l, "akai-lpd8");
MKtlGUI(mktl: l);

// index number 0 is first element
l.elementAt(\kn, 0) == l.elementsDict[\kn_1];
// key \1 is the name for the first element
l.elementAt(\kn, \1) == l.elementsDict[\kn_1];
l.elementAt(\kn, 0).action = { |el| [el.name, el.value.round(0.001)].postln };

// same thing in the extreme 3dpro, works now:
x = MKtl(\x, "*3d*");
MKtlGUI(mktl: x);
x.elementAt(\bt, 0); // -> MKtlElement('bt_1', 'button', '1')
x.elementAt(\bt, \1); // -> MKtlElement('bt_1', 'button', '1')
```
would be good to go through all descs for this possible glitch - any volunteers?
