### ISSUE TITLE
add physical labels as description of controller elements, add to tagging system

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#165]
This would result in something like that:

```
(
device: "OP-1 Midi Device",
protocol: \midi,
description: (
    \kn: [(1..4), [\blue, \green, \white, \red]].flop.collect { |desc, i|
        var num, label;
        #num, label = desc;
        (\midiMsgType: \cc, \type: \knob, \label: label, \midiChan: 0, \midiNum: num, \spec: \midiCC)
    }
)
)
```

How do we deal with multiple labels? Arrays of symbols?

**Comment by adcxyz** [comment]
in the JITLibExtensions / Halo tagging system, tags are always weights, by default 1, so you can express relative weights (e.g. this Ndef is a little noisy, that one is very noisy). this supports multiple tags extremely simply.

**Comment by adcxyz** [comment]
are there any other cases than the OP1?

**Comment by adcxyz** [comment]
is this a showstopper for 0.9.0?

**Comment by LFSaw** [comment]
no showstopper, changed milestone to later

**Comment by adcxyz** [comment]
@LFSaw ping 
- is this still open? if so, 
- are there any other cases than the OP1?
- have you tried the Halo tagging system?

**Comment by adcxyz** [comment]
no response, so closing and moving to projects.
