### ISSUE TITLE
get a list of possible shortcut names (even if devices are not there)

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#168]

**Comment by sensestage** [comment]
and available descriptions

**Comment by sensestage** [comment]
MKtlDesc seems to be doing this.

**Comment by adcxyz** [comment]
this would do it - make a method for it?
```
MKtlDesc.loadDescs;
MKtlDesc.allDescs.do { |desc| 
	var shortname = MKtl.makeLookupName(desc.idInfo);
	[desc.fullDesc.filename, shortname, desc.idInfo].postcs;
}; "";
```

**Comment by adcxyz** [comment]
even simpler:
```
MKtlDesc.fileToIDDict.keysValuesDo { |idInfo, file|
	var shortname = MKtl.makeLookupName(idInfo);
	[file, shortname, idInfo].postcs;
}; "";
```

**Comment by adcxyz** [comment]
this is obsolete now with dropping shortnames, in commit 4b3612ca03544b544adf1fcc4babff5d08004959

**Comment by LFSaw** [comment]
still, would be good to be able to have a method to list all supported devices... altered the subject of the issue accordingly.

**Comment by adcxyz** [comment]
There is one:
MKtlDesc.postLoadable
MKtlDesc.postLoaded
so close this one?

**Comment by LFSaw** [comment]
super!
