### ISSUE TITLE
check cookbook examples for correct behaviour

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#175]
they are in this repository:
https://github.com/ModalityTeam/ModalityWorkshop

**Comment by adcxyz** [comment]
Hi, 
I updated most of the cookbook examples, and they run ok now.

@miguel-negrao - can you please check the two FRP examples? they are
https://github.com/ModalityTeam/ModalityWorkshop/blob/master/cookbook/complex-copy-paste/complex-copy-paste_frp_style.scd
https://github.com/ModalityTeam/ModalityWorkshop/blob/master/cookbook/switchingActions/switchActionsFRP.scd
@LFSaw - can you please check this one: 
https://github.com/ModalityTeam/ModalityWorkshop/tree/master/cookbook/lightshow

then we can close this. 
thanks, adc

**Comment by adcxyz** [comment]
moved remaining check requests to issue #277
