### ISSUE TITLE
device definition discussion

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#178]
+ write up decision
+ write up definition to ```HelpSource/Reference/MKtl_description_files.schelp```
+ ```MKtlDesc``` quick demo
+ implement desc files in existing desc files, add test/status flag

**Comment by sensestage** [comment]
device: -> idInfo

and see #162

**Comment by sensestage** [comment]
add key:
collectives
for functionally needed groups (e.g. for OSC)

**Comment by sensestage** [comment]
deviceType:

see #173

**Comment by sensestage** [comment]
apart from source/destination pairs implented via: 61ae776f9f75972f1c41cd625b42888fdfbf7c34

**Comment by LFSaw** [comment]
maybe next time amending commits? this last commit you refer to implements one (1) character: a comma... :)

**Comment by sensestage** [comment]
ok, then since that commit...

**Comment by sensestage** [comment]
Also this issue #111 needs an entry

**Comment by sensestage** [comment]
Still some discussion whether ```deviceType``` should have that name, or another one.

**Comment by adcxyz** [comment]
it seems no one objects to deviceType, it is implemented, and all the other little issues here are done, so I close this.
