### ISSUE TITLE
Allow nil as wildcard in elementAt()

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#179]
something like 
```
elementAt(\kn, nil, 5)
```
would be great to have

**Comment by adcxyz** [comment]
in republic: 
key for 'where' param can be 
single name,
index,
list of names,
and 'all'
then with nanokontrol1, 
x.elementAt(\sl, \all, 8) could used to add
 action to set mastervol

**Comment by adcxyz** [comment]
this could be addressed nicely in NamedList, see #211

**Comment by LFSaw** [comment]
I am for the implementation with ```NamedList```.
Why ```\all```, if there is ```nil```?

**Comment by adcxyz** [comment]
for semantic clarity ;-) 
nil could also be a variable that was not assigned by accident, 
and then unexpected things would happen.

**Comment by adcxyz** [comment]
has been working for a while in desc_reorg: 
m = MKtl(\x, "korg-nanokontrol");
m.elAt([\kn, \sl], 1, [0, 1]).postcs // knobs and sliders 1, 2 of scene 1
m.elAt(\sl, nil, [0, 1]).postcs;   // first two sliders of all 4 scenes
m.elAt(\sl, \all, [0, 1]).postcs; // nil and \all work as wildcards.
