### ISSUE TITLE
add writing a string to ableton push's display

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#182]
for a starting point, see 
http://tai-studio.org/index.php/projects/sound-programming/accessing-abletons-push-device/

**Comment by sensestage** [comment]
Is there a connection to sending a string via OSC, as is used in the Manta description?
I made a StringMap class for that case in commit 5fea7f61c5202907754f3ac1d8e398c62f584947

**Comment by LFSaw** [comment]
well, it is arbitrary strings... so no :)

**Comment by sensestage** [comment]
Do you always need to send the 68 characters?

**Comment by sensestage** [comment]
main format:

```
240 71 127 21 {24+line number} 0 69 0 {ASCII char1} {ASCII char2} … {ASCII char68} 247
```

I could imagine something like:
```
argTemplate: [ 240, 71, 127, 21, 24, 0, 69, 0 ] ++ nil ++ 247
```
The 24 can be different for each line (so each line would be a different MKtlElement), and we would need a ```type: \asciiString``` with an additional element: ```length: 68```.

Then the send method could translate the string into an array of ascii numbers, fill it up to make an array of 68 elements, and put it into the argTemplate, flatten it and send it out via sysex.

**Comment by sensestage** [comment]
if the length is arbitrary, you can leave it nil, and it will just create an array of ascii characters as long as the string is.

**Comment by sensestage** [comment]
Example implementation:
This would be in ```MIDIMKtlDevice::send``` for the ```sysex``` case:

```
(
~el = (
	argTemplate: [ 240, 71, 127, 21, 24, 0, 69, 0 ] ++ [ nil ] ++ 247,
	type: \asciiString,
	length: \68,
	\ioType: \out,
	\midiMsgType: \sysex
);
);



(
~val = "hello";
if ( ~el[\type] == \asciiString ){
	var sysexMsg;
	var argTemplate;
	var fullascii;
	var ascii = ~val.ascii;
	if ( ~el[\length].notNil ){
		fullascii = Array.fill( 68, 0 );
		ascii.do{ |it,i| fullascii.put( i, it ); };
	}{
		fullascii = ascii;
	};
	argTemplate = ~el[\argTemplate].copy;
	if ( argTemplate.includes( nil ) ){
		argTemplate.put( argTemplate.indexOf( nil ), fullascii );
	}{
		argTemplate = argTemplate ++ fullascii;
	};
	sysexMsg = argTemplate.flatten;
};
);
);


(
~el = (
	argTemplate: [ 240, 71, 127, 21, 24, 0, 69, 0 ] ++ [ nil ] ++ 247,
	type: \asciiString,
	// length: \68,
	\ioType: \out,
	\midiMsgType: \sysex
);
);



(
~val = "hello";
if ( ~el[\type] == \asciiString ){
	var sysexMsg;
	var argTemplate;
	var fullascii;
	var ascii = ~val.ascii;
	if ( ~el[\length].notNil ){
		fullascii = Array.fill( 68, 0 );
		ascii.do{ |it,i| fullascii.put( i, it ); };
	}{
		fullascii = ascii;
	};
	argTemplate = ~el[\argTemplate].copy;
	if ( argTemplate.includes( nil ) ){
		argTemplate.put( argTemplate.indexOf( nil ), fullascii );
	}{
		argTemplate = argTemplate ++ fullascii;
	};
	sysexMsg = argTemplate.flatten;
};
);
);
```

**Comment by adcxyz** [comment]
moving to sleeping beauties
