### ISSUE TITLE
use argTemplate for MIDI messages

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#184]
In some cases you may use the argTemplate matching, similar to the OSCMKtlDevice.
E.g. midi devices with pitch bend implement as two buttons, both giving a pitch bend message, but with a different default value.

**Comment by sensestage** [comment]
In the current implementation of MIDIMKtlDevice single MIDIFunc's are made per type of message, not per element. This means we cannot easily make use of the built-in MIDIFunc argTemplate matching.

**Comment by sensestage** [comment]
Although the MIDIValueMatcher may be used:

```
m = MIDIValueMatcher.new( [64], { |v| v.postln } );

m.value( 64 );
m.value( 43 );
```

**Comment by adcxyz** [comment]
this could be useful for per-channel monophonic voicers.

**Comment by adcxyz** [comment]
closing and moving to sleeping beauties
