### ISSUE TITLE
OSCMKtlDevice: allow for setting ipAddress separately for device

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#185]
Ports and so on may be fixed, but ipAdrresses change for each LAN setup

**Comment by sensestage** [comment]
A similar case occurs for MIDI devices that attach to a generic USB MIDI interface.

**Comment by adcxyz** [comment]
I believe I got this with commit 7a89e3f2233ef1c1517607c05e601fd65ac86f68
Please test with  devices where it is really needed (the manta is local only):
// from example in manta desc file 
MKtl(\manta, "*manta*");
MKtl(\manta).mktlDevice.updateSrcAddr("1.2.3.4", 56789);
MKtl(\manta).mktlDevice.source; // has new numbers, disconnected

**Comment by adcxyz** [comment]
I think this is done, please reopen or fix if not.
