### ISSUE TITLE
do we really need the shortname?

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#188]

**Comment by adcxyz** [comment]
works again now, and I added MKtl.makeLookupNameFunc variable 
so one can play with different shortname functions.

**Comment by LFSaw** [comment]
saw it, looks nice....
my opinion to this question is:

it is a "nice to have" which may turn into a "must have to maintain", once more people catch on using that funtionality...

**Comment by adcxyz** [comment]
if that becomes a problem, we can remove it.

**Comment by adcxyz** [comment]
also, ``` MKtl(\myPetName, "company-productname"); ``` works already

**Comment by LFSaw** [comment]
let's keep discussions about this at one point: #210
