### ISSUE TITLE
add \page to description hinting at controller page (double/triple assignment of HW elements that can be switched between using the controller itself)

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#190]
This is useful for GUIs.
It should be an optional information for each element. If not present, it is assumed to be ```0```.
An example is in ```LaunchControlXL.desc.scd```

**Comment by LFSaw** [comment]
this is used in the MKtlGUI implementation.

**Comment by adcxyz** [comment]
hardware paging could now be moved to multiple desc files if desired: 
deviceXYZ_preset1.desc.scd
deviceXYZ_preset2.desc.scd
etc. 
how do we want to best pursue this? 
is this needed for 0.90?

**Comment by LFSaw** [comment]
closely related to #123

**Comment by adcxyz** [comment]
added an entry for hardwarePages to all devices that have them, so one can ask the desc about it. 
e.g. nanokontrol
(
hardwarePages: [1,2,3,4]
...
)

**Comment by adcxyz** [comment]
added page value to elements in all devices with hardware pages, so close with 3ccc819
