### ISSUE TITLE
MIDI: noteOn message with velocity 0 is parsed as noteOff message

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#193]
A bug in the AlsaMIDI client.

See: https://github.com/supercollider/supercollider/issues/1483

**Comment by sensestage** [comment]
fix proposed for supercollider

**Comment by LFSaw** [comment]
not our playfield... this is discussed (and fixed) in https://github.com/supercollider/supercollider/pull/1488
