### ISSUE TITLE
MIDI: implement remaining MIDIIn messages

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#195]
like

```
\midiClock, \start, \stop, \continue, \reset
```

and songSelect and so on.

**Comment by adcxyz** [comment]
I believe scott added more support for obscure midi messages, so does someone who knows about them and needs them want to finish them? if not, move this to later/optional?

**Comment by adcxyz** [comment]
moving to sleeping beauties.
