### ISSUE TITLE
add efficiency tests for MIDI responders

### ISSUE THREAD

**Issue by adcxyz** [ModalityTeam/Modality-toolkit#198]
the MIDIresponders in Modality are complex to read. 
when considering simplifying by switching to MIDIFuncs, 
the current scheme turned out more efficient than MIDIFunc, 
which was a reason for keeping them. 
-> add such tests to the documentation.

**Comment by sensestage** [comment]
argTemplate matching for controls on a device that send the same message but in a different range, like some button-based pitchbend messages on midi keyboards, the usual MFunc would provide that feature more easily.

https://github.com/ModalityTeam/Modality-toolkit/issues/184

**Comment by adcxyz** [comment]
obsolete because already switched to MIDIFuncs.
