### ISSUE TITLE
make release

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#200]
tag your releases. The name of the tag is the name of the release version in the Quarks system. Using semver (eg "1.0.1") is recommended. This provides the Quarks system with a way to list versions in the interface and to checkout a version and for people to pin dependencies to a stable release. it also provides a downloadable version on your github releases page.

**Comment by LFSaw** [comment]
I'd suggest '```0.9.0'``` for our release. I rename the Milestone accordingly.

**Comment by LFSaw** [comment]
I also set the date of the milestone to end of June. This gives us a Month to work on it.

**Comment by adcxyz** [comment]
moved to Nov 1.

**Comment by miguel-negrao** [comment]
Should a release be made ? This entails setting a tag and changing the quark file, right ?

**Comment by LFSaw** [comment]
anyone knows about this?
we should do it. now. it is stable.

**Comment by miguel-negrao** [comment]
I can look into it.

**Comment by LFSaw** [comment]
let's look together >> gitter?

**Comment by miguel-negrao** [comment]
ok, I'm there.

**Comment by LFSaw** [comment]
since current version is 0.1.0, we should tag it 0.2.0

**Comment by LFSaw** [comment]
together with @miguel-negrao, I created an initial change log. Please comment/change until Wednesday, 24.5.2017.
https://etherpad.wikimedia.org/p/modalityShortlog

**Comment by miguel-negrao** [comment]
Thanks @LFSaw for going through the log. It looks good to me.

**Comment by miguel-negrao** [comment]
@LFSaw show we release now ?

**Comment by LFSaw** [comment]
Released. Congratulations to all! 
https://github.com/ModalityTeam/Modality-toolkit/releases/tag/v0.2.1
