### ISSUE TITLE
add descriptive fields to desc files

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#203]
vendorUrl: <url to product at vendor homepage>
manual: <url to manual>
description: <short description of device>
features: <short list of features, each line is one feature>
notes: <markdown-formatted notes>

**Comment by LFSaw** [comment]
this is useful for automatic generation of controller webpages

**Comment by bhabbestad** [comment]
I will I will add 'features' to those controllers missing this item over the next days.
I can also start to update the  'type' table according to the naming convention.

**Comment by LFSaw** [comment]
Super:



> On 27. May 2015, at 00:29, bhabbestad <notifications@github.com> wrote:
> 
> I will I will add 'features' to those controllers missing this item over the next days.


make sure to add the features like this:


---
<other stuff>
features: |
    + one feature,
    + another feature,
    + and yet another feature
<other stuff>
---

:)
	Till

**Comment by adcxyz** [comment]
format suggestion within MKtlDesc: 
```
(name: \xyz, 
protocol: \hid, 
moreInfo: (
  vendorUrl: "https://vmeter.com", 
  manual: ""https://vmeter.com/rtfm.html",
  features: [
    <name1>: "<text about the feature1>", 
   ...
), 
...
)
```

**Comment by LFSaw** [comment]
:+1: 
moreInfo >> deviceInfo ?

**Comment by LFSaw** [comment]
I now settled on the following optional information items:

```
deviceInfo: (
	vendorURI: "http://vendor/product",
	manualURI: "http://manual.pdf",
	description: "Short sentence on what a great controller this is.",
	features: [
		"23 colorblinding pads",
		"42 invisible sliders",
	],
	notes: "Make sure the device is in total-recall mode!",
	type: [\pad, \slider],
	hasScribble: false // see e.g. ableton push for a device that has one
),
```
