### ISSUE TITLE
Fix affiliations on webpage

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#205]
currently reads:

```
The work has been funded by: Norwegian Arts Council, City of Bergen, Kulturkontakt Nord, Nordic Council, XX Dutch funds.
```
This should also include a link to the funding institute.

Please hand over the assignee, once you did your part.

**Comment by sensestage** [comment]
done my part!

**Comment by LFSaw** [comment]
this is closed with ModalityTeam/ModalityTeam.github.io@3e22ccff30cd1ce47d145f820a50c0d15a2dd24c
