### ISSUE TITLE
MKtl refactor branch: link between desc information and actions is broken

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#208]
in commit 1ed99dd this seems to be broken:

```
MKtl('nnkn20', "korg-nanokontrol2");

MKtl('nnkn20').trace;
// move first slider, does not recognise it... :/

MKtl('nnkn20').trace(false)


// does it do the action?
MKtl('nnkn20').elementAt(\sl, 0).action = {|el|
	el.value.postln
}
// nothing here... :(

// in desc file, everything seems to be ok...
MKtl('nnkn20').desc.openFile;

// also, it seems to read in the values correctly
MKtl('nnkn20').elementAt(\sl, 0).elementDescription;
// -> ( 'midiChan': 0, 'midiMsgType': cc, 'type': slider, 'midiNum': 0, 'elemKey': sl_0, 'style': ( 'column': 7, 'row': 1 ), 'spec': midiCC )

```

**Comment by adcxyz** [comment]
just sitting at the MIDI side of MKtl ...

**Comment by adcxyz** [comment]
closed with #768eba0da312e23349ba2b7680007e3b560fbf11

**Comment by LFSaw** [comment]
768eba0da312e23349ba2b7680007e3b560fbf11 (no '#' for commits...)

**Comment by LFSaw** [comment]
ah ok, thought I've seen this working already...

**Comment by LFSaw** [comment]
did not help for me, sorry...

**Comment by adcxyz** [comment]
ok, will look into it asap

**Comment by LFSaw** [comment]
sorry... :8ball:

**Comment by adcxyz** [comment]
works for cc and noteOn/Off, others to follow soon.

**Comment by LFSaw** [comment]
can I help? tomorrow I might have some spare minutes...

**Comment by adcxyz** [comment]
if you can, please check that your interfaces work again, enable polytocuh and try the push- see tests/alllcontrollers

**Comment by adcxyz** [comment]
merged all changes from current master, and nearly everything except 
adding the missing midi msgTypes from midimktlbranch. (this needs a bit more care).
If you like, please test current refactor_test2 branch - except for allNotesOff, 
and sysrt things like songStart etc, it should listen to everyt message.
sendback not tested yet, may work partially. 

please commit the tests you use, so I can check them here;
and looking forward to moving this to master soon if tests runs well :-)
best adc

**Comment by LFSaw** [comment]
I'll close this issue now because it is explicitly coined towards the MKtl refactor branch.
