### ISSUE TITLE
how to listen and send to a MIDI device with multiple ports in one MKtl?

### ISSUE THREAD

**Issue by adcxyz** [ModalityTeam/Modality-toolkit#209]
The Steinberg CMC PD is a case: 
* it registers with three in ports, no less, 
     all the same name (and Port 1 Port 2 Port 3)
* it sends on the first two ports 
* no idea yet which ones it receives on.

When you create it with MKtl('stnb0'), 
it takes a random one of the ports (dict.detect ... )
```
MKtl.find(\midi);
MKtl('stnb0', "steinberg-cmc-pd");
MKtl('stnb0').trace(true); // does
MKtl('stnb0').mktlDevice.midiKeyToElemDict.size;

MIDIFunc.trace(true);

// get the three, nothing else connected
~myuids = MIDIClient.sources.collect(_.uid);
-> [ -1808886748, -390653982, 730086740 ]

MKtl('stnb0').mktlDevice.srcID; // is a different one next time

// One way to handle this would be to match for severl uids in the MIDIFunc(s):
MIDIFunc.cc({ |... args|
	if (~myuids.includes(args.last)) {
		// "from my device: ".post; args.postln;
		// do things here
	}
}, srcID: nil);

MIDIFunc.noteOn({ |... args|
	if (~myuids.includes(args.last)) {
		// "from my device: ".post; args.postln;
		// do things here
	}
}, srcID: nil);
```
good like that? 
other ideas? 
also, no idea how to send values back yet when multiple return uids.

best adc

**Comment by LFSaw** [comment]
I thought we had some agreement on this made based on the ```ableton-push``` device, I cannot find it anymore... :/ @sensestage , @woutersnoei ?

**Comment by sensestage** [comment]
You can specify the port in the device description - all this is in the midimktldevice branch.

And then you can make a combined MKtl, like adcxyz worked out.

**Comment by adcxyz** [comment]
ok, then it should be easy to support arrays there

**Comment by adcxyz** [comment]
got further with this in d490301de2f19780c0d416e5621920b6a3ec9a27
still open: support multiple uids for each srcID and destID.
e.g. the Steinberg CMC devices do that.

**Comment by sensestage** [comment]
In MIDIFunc, the srcID cannot be an Array; they need to be explicit.

**Comment by adcxyz** [comment]
yes, we can set it to nil, and match inside the midifunc.

**Comment by adcxyz** [comment]
more progress here, not finished yet: 
MKtlLookup now first sorts all ports/devices by idInfo into one item in midiAll; 
then transfers single-device/single port ones to MKtlLookup.all for use.
items with multiple sources/dests are then split by whether the port name are identical
(-> several identical devices) or not (one device, multiple ports) or both.
Not done yet: 
matching with multiple MKtlDescs for the same device: 
separate descs for each port, and for each port/hardware preset/mode.

**Comment by adcxyz** [comment]
MIDIMKtlDevice by design choice now listens to only one src/dest port (finished with c1c2058 ), 
so supporting multiple ports in single MKtl should be done with CompMKtl.
