### ISSUE TITLE
Deal with MIDI devices that appear as two separate devices

### ISSUE THREAD

**Issue by miguel-negrao** [ModalityTeam/Modality-toolkit#21]
MIDIMKtl('sprc0', 8454149, 8454144);  // SuperCollider
   MIDIMKtl('cncn2000', 1310720, 1310720);  // iCON iControls V2.00
   MIDIMKtl('mdth0', 917504, 917504);  // Midi Through
   MIDIMKtl('cncn2001', 1310721, nil);  // iCON iControls V2.00
   MIDIMKtl('sprc1', 8454150, 8454145);  // SuperCollider
   MIDIMKtl('syst0', 0, nil);  // System
   MIDIMKtl('syst1', 1, nil);  // System

icon iControls appears has two devices. Possibly midi out is on the second one... have to investigate

**Comment by adcxyz** [comment]
this may be closed with commit e94cde3f7304ef72e657ca3719b920dedfed7724;
do we have any devices here that show that behavior to test, 
and write a merge example / .comp.scd file for it?

**Comment by adcxyz** [comment]
now works with single srcID and destID - still to test for multi-uids for src/dest.

**Comment by adcxyz** [comment]
// new support for multiport midi devices:  srcID CAN be an array now ;-) 4e3ac4b
one can tell the MKtl which portIndex to listen to and to send to.

```
MKtlDevice collects all ports that fit to its description, 
and one can say which one to use, by portIndex.

// if multiple ports were found, MKtl asks for a portindex:
m = MKtl(\qn1, "keith-mcmillen-qunexus");
posts: 
-> MKtl('qn1'): multiple uids found: [ -451410899, 1447455117, 2053013113 ]. 
please provide the index to listen to:
MKtl('qn1').listenTo( _index_ );

// so one can set which port to use for listening and sending 
MKtl('qn1').listenTo( 0 ).sendTo( 0 );
m.trace;

// the Mktl still knows all its ports, 
m.mktlDevice.srcID;
m.mktlDevice.dstID;

// and the responders and out have the correct IDs:
m.mktlDevice.responders.control.srcID
m.mktlDevice.midiOut.dump

// to use a second port on the same device, one sets different portIndices:
// E.g. make a second qnexus device for port 3 which is an CV/gate interface. 
// description not adapted for that yet.
n = MKtl(\qn3, "keith-mcmillen-qunexus");
MKtl(\qn3).listenTo( 1 ).sendTo( 1 );
```

**Comment by LFSaw** [comment]
I concider this issue closed, multi-(MIDI)device for one hardware device is discussed in issues #222
