### ISSUE TITLE
we need named list or ordered envir

### ISSUE THREAD

**Issue by adcxyz** [ModalityTeam/Modality-toolkit#211]
we have several different places where we want named items AND keep their order:
- keep hierarchical order and sequence  from desc files in 
  MKtl.elements
- future - save presets by ordered names
- order in which devices are registered in e.g. HID.available

There are several implementations of this already, in OE in wslib, 
Julian and I have written different ones  for several projects,
MFunc has its own scheme which could be abstracted out ...

try to ask for that in 3.7? 
make our own for modality?
make one in a small separate quark (that may contain uses such as MFunc)?

opinions plz :-)

**Comment by adcxyz** [comment]
I would prefer the small separate quark and later inclusion in 3.7
or having a new OrderedSet, OrderedDictionary supported by primitives in SC itself, 
which has subclasses like OrderedEvent etc.

**Comment by LFSaw** [comment]
I guess, non of these

```
SortedList
OrderedIdentitySet
```

help?
Then I'd make a separate quark.

**Comment by adcxyz** [comment]
no they are both not sufficient. will make a quark then!

**Comment by LFSaw** [comment]
Name should be ```SortedDict```, maybe?

**Comment by telephon** [comment]
should be in common, I think

**Comment by LFSaw** [comment]
I'm all for what @telephon said... however, I think a good way to introduce this is via a separate quark.

**Comment by telephon** [comment]
Yes, now that we have git in the Quarks system it may be possible to move things around. I used to hesitate, because you'll get a duplicate class error with different versions if you do.

**Comment by LFSaw** [comment]
how about a "dev"-version in a git quark which is meant to be integrated into commons, once it is fully tested by, say, 10 people?
it doesn't even have to show up in the public quarks listing...

**Comment by telephon** [comment]
good idea. Needs a good design, but would make develop things easier.

**Comment by adcxyz** [comment]
thanks for discussion, completely agree. 
for now, I put a first sketch in the refactor branch so I can keep going with it - please test and comment!
9f99b3f8b8c70fa400258bb6f2b9683e0ee3a5ce

**Comment by adcxyz** [comment]
reminder: 
for now, I put a first sketch in the refactor branch so I can keep going with it 
* Please test and comment!

**Comment by adcxyz** [comment]
maybe not worth holding up the 0.90 release for it, so moved to later/optional.

**Comment by adcxyz** [comment]
move to sleeping beauties.
