### ISSUE TITLE
MIDIMKtlDevice: get destUID to work again in MKtl_refactor branch

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#213]
currently posts 

```
WARNING: MIDIMKtlDevice:	No MIDIOut destination with USB port ID nil exists!please check again.
```

for a ```korg-nanokontrol2``` which definitely has a dstOut.

**Comment by sensestage** [comment]
Also here: please merge in my changes that I made in the midimktldevice branch. I did quite a bit of work on this.
