### ISSUE TITLE
MKtlElement: add time slot

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#214]
store time value as it is provided by (OSC/MIDI/HID)func

**Comment by LFSaw** [comment]
ok, so I thought of adding a timestamp to ```MKtl(Abstract)Element``` as there is a time argument provided at least for OSC messages which we should pass through. Now the question arises if we want to populate the timestamp as well for other protocols like MIDI or HID.

I think it is useful, however, it adds overhead to the message evaluation service (not that much).

on my machine:
```
{10000.do{Process.elapsedTime}}.bench(false);
-> 0.0017589269991731
```

opinions? @sensestage @miguel-negrao @adcxyz ?

**Comment by adcxyz** [comment]
good idea, could be called
var <lastUpdateTime 
and be set here:
 value_ { 
... 
lastUpdateTime = Process.elapsedTime
}

**Comment by adcxyz** [comment]
done in e9b3f0155642431e02e404574dc38dcd1c7702dd

**Comment by LFSaw** [comment]
This is partly good, however, it would be good to be able to set it from within the ```(OSC)responder```: OSC provides timestamped messages by itself, no need to get the time for this again :)

**Comment by adcxyz** [comment]
well if you set the value from code elsewhere (e.g. from a KtlLoop), you also want a timestamp, or not?

**Comment by adcxyz** [comment]
hi, some tests:
// ask process for time
bench { 1000000.do { Process.elapsedTime; }; }; // -> 0.16 sec
// store in a global dict, then look up
q = (); q[\time] = Process.elapsedTime;
bench { 1000000.do { q[\time] }; }; // -> 0.15 sec
 // lookup of a class variable
bench { 1000000.do { Server.local }; }; // 0.11 sec

my 2c: 
asking again for current time is very cheap, 
and IMO no reason to worry about speed here.
so keep it as is, or am I missing something?

**Comment by adcxyz** [comment]
and close the issue ;-) ?

**Comment by LFSaw** [comment]
IMHO it is not about asking again, it is that you want to have the precise time on which the message arrived/was scheduled, *not* when it arrives at the end of the OSC stack since we do not know how much time passed in between.

**Comment by adcxyz** [comment]
any new suggestions for this one, or is the first pass good enough for the 0.90 release?

**Comment by LFSaw** [comment]
I think it is good enough. I added a new issue about this at #235
