### ISSUE TITLE
A minor suggestion regarding naming of classes and methods

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#218]
At some point, we agreed to have both class and method names explicitly typed out, unless they are used a lot in end-user (live-)coding.
With this in mind, I'd suggest renaming 

```
	MKtlDesc >> MKtlDescription
	MIDIMon  >> MIDIMonitor
	HIDMon   >> HIDMonitor
	OSCMon   >> OSCMonitor
```

**Comment by LFSaw** [comment]
@adcxyz : 
> I thought about these and decided to model the MKtlDesc name on SynthDesc, 
and call it desc consistently in all variable names, method names and lookup keys.
OSCMon, MIDIMon and HIDMon will certainly be used for live coding -
visualizing controller streams is great for understanding what is going on 
and for entertainment and/or art.

**Comment by LFSaw** [comment]
> I thought about these and decided to model the MKtlDesc name on SynthDesc,
and call it desc consistently in all variable names, method names and lookup keys.

ok.

> OSCMon, MIDIMon and HIDMon will certainly be used for live coding -
visualizing controller streams is great for understanding what is going on
and for entertainment and/or art.

I nevertheless find the name ```*Mon``` rather not telling anything... would prefer ```*Monitor```. Any other suggestions?

**Comment by LFSaw** [comment]
@tapage ? @sensestage ?

**Comment by bhabbestad** [comment]
I support full length name for clarity

**Comment by adcxyz** [comment]
OSCMonitor renamed in 06bbb5b313872d79f2d82ebe8b4a8ff18c552971

**Comment by adcxyz** [comment]
except OSCMonitor exists in wslib, so roll back

**Comment by LFSaw** [comment]
@woutersnoei , what's your take on this?

**Comment by woutersnoei** [comment]
I'm for OSCMonitor in fact, indeed "Mon" sounds a bit vague. adc's OSCMon is much nicer than wslib OSCMonitor anyway, I'll remove or rename it there.

**Comment by LFSaw** [comment]
reverted reverted commit, so now it is called ```OSCMonitor```.
