### ISSUE TITLE
merge MKtl_refactor_test2 to master

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#229]
As there is a _lot_ that happened in MKtl_refactor_test2, as well as in master, I suggest the following:

```
  ^ ^   
  | |
  o |	XXXXXXX		merge MKtl_refactor_test2 to master
 /| |
o | |	41431ad		prev. head of MKtl_refactor_test2
| | |
| o |	XXXXXXX		revert master to 2a4c460
| | |
| | o	XXXXXXX		copy of all contributions happening between 2a4c460 and 41431ad
| | | 
| |/ 	[branch to "altMaster"]
| | 
| o 	3c91105		prev. HEAD(master) Merge branch 'master' into midimktldevice
. . 
. . 	[lots of stuff happening here]
. . 
| | 
|/  	[branch to "MKtl_refactor_test2"]
|
o 	2a4c460		initCollectives for OSC
```

**Comment by adcxyz** [comment]
thanks for figuring that out, sounds like a very good way to go!

**Comment by LFSaw** [comment]
I did the merge now with two alterations:

1. I did not do a branch but a Tag of the old state of master: https://github.com/ModalityTeam/Modality-toolkit/releases/tag/altMaster-pre09
2. I had to manually reset to pre-branch ( ee1f38a ) and merge MKtl_refactor_test2 (  	d575e55 )

however, everything is now in working condition.
