### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#232]
We need to ensure that a similar set of helpfiles on how to create a description file, cookbook examples, etc. work with the new branch

**Comment by LFSaw** [comment]
things are quite straight forward. 
I'll have a look at it after switching the master branches.
Please feel invited to do the same.

**Comment by adcxyz** [comment]
I did half of the How to ... OSC ... file already, happy if others take the other files.

**Comment by adcxyz** [comment]
OSC file done by now, MIDI file 90%, sourcePortIndex still to finalize.

**Comment by adcxyz** [comment]
ok, MIDI, OSC, HID How to files done now for current desc format. (still using ```description:```, not yet ```elementsDesc: (elements: )```

**Comment by adcxyz** [comment]
Can someone please go through the existing documentation to create two lists: 
* list of docs that need updates
* list of which topics still need documentation, plus suggestion which/how?

**Comment by adcxyz** [comment]
seems well represented in 257, so closing this one.
