### ISSUE TITLE
single-port MIDI descs share global information

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#233]
this leads to potential irregularities between different ports.
A possible solution to this is to introduce a hierarchical desc-file system:

```
/MKtlDescriptions
+ ControllerWithOnlyOnePage.desc.scd
+ DIRECTORY: MultiPageController
     + MultiPageController.desc.scd
     + MultiPageController-page1.subDesc.scd
     + MultiPageController-page2.subDesc.scd
```

other ideas are welcome, however should be implemented in a separate branch _after_ the merge of refactor2 to master.

**Comment by adcxyz** [comment]
the advantage of that would be NOT copying global info on the device between multiple files, which always goes out of sync.

**Comment by LFSaw** [comment]
Just came to my mind that, in case of *reading in* the files, the more specific one's are more significant than the one's sharing global information. much like ```.h``` and ```.cpp``` files, where the headers are possibly linked to multiple files whereas the source files contain the actual information.

This'd mean we'd rather have a tructure like this:

```
/MKtlDescriptions
+ ControllerWithOnlyOnePage.desc.scd
+ DIRECTORY: MultiPageController
     + MultiPageController.parentDesc.scd
     + MultiPageController-page1.desc.scd
     + MultiPageController-page2.desc.scd
```

and one of the page descs contains a pointer to the global desc:

```
(
parentDesc: "MultiPageController", // pointer to parent

deviceInfo: (
    additionalInfo: "this also overwrites information given in parent"
),

portName: "Port 1",
modeName: "Preset AB",

description: (
[...]
)
)
```

**Comment by adcxyz** [comment]
completely agree, makes sense to have them hierarchical. 
It just makes the file reads/lookups a bit more complex. 
I'd like to finish the flat reading of files and matching with different portIndices first, 
then move to the better clearer org.

**Comment by adcxyz** [comment]
It was easier to do the hierarchical files first, see 34960e6

**Comment by adcxyz** [comment]
34960e6 closes this issue.
