### ISSUE TITLE
It should be possible to combine MKtls

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#234]
see #221 for reasons.

**Comment by adcxyz** [comment]
yes, we should look at the composite MKtl example again and turn it into classes/methods, so one can just say MKtl.compose(\xyz, MKtl(\x), MKtl(\y), MKtl(\z));

**Comment by adcxyz** [comment]
started on simple MKtlComp class with dcfde6d

**Comment by adcxyz** [comment]
updated CompMKtl in 42d2041. 
CompMKtl will likely want more of the MKtl interface - waiting for suggestions and use cases.
