### ISSUE TITLE
HIDMKtlDevice and its HID should be decoupled for flexibility

### ISSUE THREAD

**Issue by adcxyz** [ModalityTeam/Modality-toolkit#236]
in the new soft paging concept (see issue #48), multiple MKtls are used as software pages for the same physical controller. this works with MIDI and OSC, but not immediately with HIDs: 
The MKtl's element actions are put into the HID inside the mktlDevice, which makes its use less flexible.
One way around this would be using the HID object only as an information container (so it can be shared by multiple MKtls), and then having a single HIDFunc which listen to the HID's address, and routs the incoming messages to the elements by dict lookup, as in MIDIMKtlDevice.
Then MKtl device polyphony/paging is only turning the HIDFuncs on and off! 

Comments welcome :-)

**Comment by adcxyz** [comment]
code sketch showing the idea:
```
x = MKtl('x', "thrustmaster-run-n-drive");

// make lookup dict once
~elemsByUsage = ();
x.elementsDict.keysValuesDo { |key, elem|
	var desc = elem.elemDesc;
	var elemUsageKey = "%_%".format(desc.hidUsagePage, desc.hidUsage).asSymbol;
	~elemsByUsage.put(elemUsageKey, elem);
};

// lookup while listening to whole device:
HIDdef.usageID(\gp1, { |val, devVal, elemKey, usagePage|
	var elemUsageKey = "%_%".format(usagePage, elemKey).asSymbol;
	var elem = ~elemsByUsage[elemUsageKey];
	var elemName, elemVal;
	if (elem.notNil) {
		elemName = elem.name;
		elem.valueAction_(val);
		[elemUsageKey, elemName, val.round(0.001)].postcs;
	} {
		"no elem for %\n".postf(elemUsageKey);
	};
}, [1, 9]);
```
With such a solution, multiple MKtls can listen to the same physical HID, and can be dis/enabled simply by turning their HIDFuncs on and off.

**Comment by adcxyz** [comment]
a simpler first step to make HID polyphonic:
in HIDMKtlDevice:open, 
first find out if this HID is already open, 
if yes, use the existing one, 
if no, make a new one. 
In initElements: 
create the exact element actions + trace (in hidele.action = ...) first, 
politely add them to hidele.action with addFunc, i.e.
hidele.action = hidele.action.addFunc(newaction);
then keep these actions in vars so one can disable/free them again with removeFunc.

**Comment by adcxyz** [comment]
```
// steps toward this in commit 0d49b7c - works but likely not the best solution.
MKtl.find(\hid);
MKtl('x', "saitek-impact-gamepad");
MKtl('x').trace;
MKtl('x').mktlDevice.disableElement(\bt_5);
MKtl('x').mktlDevice.disable; // disables all elements
MKtl('x').mktlDevice.enable;  // enable them again
```

**Comment by LFSaw** [comment]
```MKtl('x').elementAt(\bt, 5).disable; // alternative syntax for enable/disable```
