### ISSUE TITLE
name clash OSCMonitor

### ISSUE THREAD

**Issue by miguel-negrao** [ModalityTeam/Modality-toolkit#237]
OSCMonitor is in wslib since 2011, OSCMonitor was added to modality in 2015. It is not unlikely that people (i.e. me, @woutersnoei , anyone using Unit Lib) will use Modality and wslib at the same time. Since the version in wslib is older, I would suggest renaming the version in Modality. Unfortunately, SuperCollider doesn't have namespaces to avoid these problems...

**Comment by woutersnoei** [comment]
Hi Miguel, thanks for noticing, we discussed this already at the Kopenhagen sessions, and agreed that I will change the name of OSCMonitor in wslib. Will do so soon (may need to figure out where to update my quark these days).

**Comment by miguel-negrao** [comment]
Great ! Your quark is here: https://github.com/supercollider-quarks/wslib

**Comment by adcxyz** [comment]
I would not mind going back to OSCMon, MIDIMon etc ;-) see #218.

**Comment by LFSaw** [comment]
@woutersnoei , could you rename your class, please?

**Comment by adcxyz** [comment]
@woutersnoei, do you want to rename, or should we rename in Modality-toolkit?
