### ISSUE TITLE
desc file format final redefinition - proposal

### ISSUE THREAD

**Issue by adcxyz** [ModalityTeam/Modality-toolkit#238]
Dear all, 

please read the and comment on the 4 files in:
https://github.com/ModalityTeam/Modality-toolkit/tree/master/Modality/discussion/redef_proposal

Of the currently open issues, 9-12 involve the desc file conventions and propose redesigns, unification,s standardizations. I read them all and tried to integrate them as fully as possible into a new set of conventions based on the things proposed:
#178 deviceType key
#111 initialisation messages -> specialMessages key
#171, #102 naming standards for elementDesc keys
#90 -> snapbackValue, releaseMode keys
#130 better hierarchy for elementGroups, simple options to add info keys for groups
parentDesc key to support shared desc info for multiple desc files (multiport, hardwarePages)
 #103 desc file templates should be easy now

still missing a good idea:
#131 how to combine \noteOn, \noteOff etc in desc files and then in MKtlElement and MKtlGUI  implementation

also not yet included: 
rewrite as keyValueArrays as proposed in #23 

Many of the recently solved details already work now, but still 
this redesign would involve some more implementation reorg in MKtlDesc.

I would be very happy to hear comments on the overall design first, 
and once that is reasonably agreed on, happy to discuss details...
As this is before the first full release, it seems to be a very good time
to ensure the fundamental logical structure of descs is really solid.

Thanks, adc

**Comment by adcxyz** [comment]
Bit more explanation: 
Actually, 90 percent of it is definitions/conventions only, 
which are all based on maximum clarity of names - e.g. IMO 
deviceName is always the name of the device, whether tech or user-given,
idInfo is always exactly the info needed to identify a device, 
     (which can be just the deviceName, but can also be a dict)
deviceType is clearer than type, 
elementType is clearer than type,
buttonMode = toggle/momentary is clearer than mode = push/toggle,
releaseMode = hold/snapback is clearer than snapback = true
snapbackValue says what it is, 
elementsDesc is clearer description, etc. 

the only technical change is that elementsDesc (FKA description)
now has an entry for elements (which is the dict or list of elements), 
and space for all other things the corresponding elementGroup should know, 
such as: 
are there any values my elements share, (midiMsgType, midiChan, elementType etc)
are there any other groupings of my elements, (mixer channels on faderboxes), 
are there any collectives to build for my elements which are set/sent by common message, 
etc.
This extra depth in elementsDesc is the only thing requires rewriting how elements are built:
replacing former 'description' with new elementsDesc.elements, 
and applying the newly possible other data to the group being made.

**Comment by adcxyz** [comment]
In current master everything BEFORE this redesign already works and can be tested, 
so I will try to get this redesign working in branch desc_redef.
You are highly welcome to help :-)

**Comment by bhabbestad** [comment]
Great work Alberto

this seems pretty clear, regarding naming conventions, I find its easy to follow the logic 
of these adaptions.

I also checked this one out:
https://github.com/ModalityTeam/Modality-toolkit/blob/master/Modality/discussion/desc%20file%20info.md

and it seems that we forgot the piano-keyboard vs laptop keyboard distinction.

I cannot remember what we decided on - MIDIKeyboard vs HIDKeyboard is a bit clunky, maybe..

b

14. sep. 2015 kl. 11:30 skrev Alberto de Campo <notifications@github.com>:

**Comment by adcxyz** [comment]
Does anyone else have any opinions on this?
Or should I just go ahead?

**Comment by adcxyz** [comment]
hi bjoernar, 
thanks for the reminder, I did add \midiKeyboard and \hidKeyboard to deviceTypes now.
maybe not elegant, but at least very clear.

**Comment by LFSaw** [comment]
this is really excellent, thanks @adcxyz !
Today, I read this: https://en.wikipedia.org/wiki/Continuous_integration#Best_practices on development and I had this idea that we should somehow be able to make this change of desc-files _not_ in a big block but rather in small steps... such that the integration does not become a nightmare as we had it before with the re-factor branch. 

It might be worth to therefore separate the changes in smaller chunks like

+ changing names to better ones
+ hierarchy for elementGroups
+ desc file templates

and make those changes in sequence, in separate "topic/xxx" branches that are easy to merge with the master. This way, we all have the opportunity to take out bits and pieces to work on, and, more important, we will not fully break auto-merging.

Thoughts?

**Comment by adcxyz** [comment]
yes, absolutely for smaller steps. The refactor would have been a lot less headache if that had been doable!

+ when changing names in elements for better ones, one can implement/update and use: 
```
MKtlDesc.isValidElemDesc
MKtlDesc.isElementTestFunc
```
+ when changing names in descs generally for better ones, one can implement/update and use: 
```
MKtlDesc.isValidDescDict
MKtlDesc.isValidHIDDesc
MKtlDesc.isValidMidiDesc
MKtlDesc.isValidOSCDesc
```
+ when redoing hierarchy for elementGroups, one can implement 
```
MKtlDesc.isValidGroupDesc
```

**Comment by adcxyz** [comment]
One more thought  - would be good if the implementation and the automated tests for these are done by different people. Any volunteers?

**Comment by adcxyz** [comment]
Still waiting for people to read the four proposal files and comment ...

**Comment by adcxyz** [comment]
name changing mostly done by now, so of tills three points, there remain:
* hierarchy for elementGroups
* desc file templates
I can try getting the elementGroups redefined in redef branch next.

**Comment by LFSaw** [comment]
```
deviceName: "LPD8", 			// user-readable name
```
this should maybe reflect the file naming convention 

```
vendor product
```

?

**Comment by LFSaw** [comment]
```
	'sharedValues': (),
	sharedValueGroups: (...)
```
the term ```value``` is a bit misleading... maybe something like ```sharedInfo```? 
not really happy with this one either... suggestions?

**Comment by LFSaw** [comment]
```
elements: [
		\kn -> (
			sharedValues: (elementType: \knob, midiMsgType: \control),
			elements: [
				\1 -> (midiNum: 1),
				\2 -> (midiNum: 2)
			]
		),
		\pad -> (
			sharedValues: (elementType: \pad, midiMsgType: \noteOnOff),
			// ...
			elements: [
				\1 -> (midiNum: 36),
				\2 -> (midiNum: 37),
				// ...
			]
		)
	]
```

this will basically break json-compatibility. why is an ordered association array needed here?

**Comment by LFSaw** [comment]
```
/* specialMessages: a dict of special messages to send to the device */
specialMessages:
```

naming... 

```
specialDeviceMessages:
```
?

**Comment by LFSaw** [comment]
```
	// a reserved name for comment-like things
	'info': (
		text: "anything useful for this group of elements",
		anyKey: [\what, \so, \ever],
	),
```


This seems to me like just-in-case programming :)

**Comment by adcxyz** [comment]
yes it does. 
seemed to make sense to have any extra text info semi-out of the way, 
but fine with me to drop that. it is not used for anything programmatically anyway.

**Comment by adcxyz** [comment]
* specialMessages -> specialDeviceMessages : 
yes, possible. not sure it is clearer

* this will basically break json-compatibility. why is an ordered association array needed here?

+ json-compatibility: many descs create things with sc code, and should be rendered to a flat, 
json-compatible formats anyway, so does the assocArray really create a problem here?

+ why assocArray: 
An ordered association array gets converted to an MKtlElementgroup with exactly that 
order of elements, and the assoc-keys as names. 
dictionaries will be ordered alphabetically only, which may not be the clearest order, 
and can create orders like ```[bt_1, bt_10, bt_11, bt_12, bt_2, bt_3, ...]```. 
We could also support keyValueArrays here:
```[
\1, (elementType: \button, ...),
\2,  (elementType: \button, ...),
]```
 would that be better than assocArrays?

**Comment by LFSaw** [comment]
> json-compatibility: many descs create things with sc code, and should be rendered to a flat, json-compatible formats anyway, so does the assocArray really create a problem here?

JSON supports Basic datatypes (Int, Float, ...) and Arrays, Dictionaries, and Strings (no separation between String and Symbol). An "ordered Dictionary" is a special datatype that is not supported and we'd need to find a non-straightforward way to represent that. But maybe I am just overly protective here...

**Comment by adcxyz** [comment]
MKtlElementGroup offers access by name and by index, which is a big semantic and usability plus. So we need some way to notate for each element or group in the desc what its local key is, 
and what its index is.
index is obvious in arrays, 
key is obvious in dicts, 
both are obvious in assocArrays, 
or another convention of array containing names.  
```
// array of assocs - unambiguous, name and index clear
[ (\a -> (x: 1, y: 2), \b -> (x: 3, y: 4) ] 
// array of open key, val pairs  - ambiguous whether key, val, key, val, or just val, val, val
[ \a, (x: 1, y: 2), \b, (x: 3, y: 4) ]
// array of pair-arrays, unambiguous, convention that name = x[0], val = x[1], a bit bureaucratic
[ [\a, (x: 1, y: 2)], [\b, (x: 3, y: 4)] ]
// if they must be dicts, key can be inside the dict - does not work if val is array
[ (key: \a, x: 1, y: 2), (key: \b, x: 3, y: 4) ] 
```
// any other notations options worth considering?

**Comment by adcxyz** [comment]
result of discussion with Till:
* we keep array of assocs, figure out how to keep that in json later
* dict of shared element properties in MKtlElementGroup is now 
 sharedProperties: (\elementType: \knob)
* collectives are now called deviceIOGroups

**Comment by adcxyz** [comment]
One more option worth considering that may by best for json
```
[ 
    (\a -> (x: 1, y: 2), 
    \b -> (x: 3, y: 4) 
] 
// can also be written as:
[ 
    (key: \a, x: 1, y: 2), 
    (key: \b, x: 3, y: 4) 
] 
```
key key could also be 'name', and would only be the key within the local hierarchy; 
elementKey gets put in later automagically when build the hierarchy.
@LFSaw - would that be preferable over the assocArray style?

**Comment by LFSaw** [comment]
imho we should concentrate on a nice representation in SC now, JSON is' später. :)

**Comment by adcxyz** [comment]
done in desc_reorg branch, finished with 1e978e7.
