### ISSUE TITLE
GeneralHID: basic examples fail and throw misleading error

### ISSUE THREAD

**Issue by telephon** [ModalityTeam/Modality-toolkit#239]
This is a bit of a show-stopper for Modality, so I added it here – we are about to release 3.7.0 and it would be nice to have this up and running, no?

https://github.com/supercollider/supercollider/issues/1304

**Comment by adcxyz** [comment]
In current 3.7 GeneralHID is removed already, so I think this is solved - Modality is best for 3.7 onward, not sure how much backward compatibility toward 3.6 etc we even want.

**Comment by adcxyz** [comment]
no one seems to object, so I close this one.
