### ISSUE TITLE
Fix EOWave ribbon description file

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#24]

**Comment by LFSaw** [comment]
initialisations:

CC 1 66 0 << full scale continuous
CC 1 66 1 << full scale half tone
CC 1 66 2 << 4 octaves continuous
CC 1 66 3 << 4 octaves half tone

CC 1 70 0 << max on LED
CC 1 70 1 << min on LED

CC 1 68 <num> << base note   to num
CC 1 72 <num> << pressure CC to num
CC 1 73 <num> << pad      CC to num
CC 1 69 0 << pad FM destination, pressure on CV
CC 1 69 1 << pad AM destination, pad      on CV
CC 1 65 <num> << waveform: (
	saw: 0,
	square: 1,
	tri: 2,
	sine: 3,
	noise: 4
)

CC 1 67 0 << Audio Out is Oscillator
CC 1 67 0 << Audio Out is CV

**Comment by adcxyz** [comment]
who has one and can finish this?

**Comment by LFSaw** [comment]
it is assigned to me, I have one.

**Comment by adcxyz** [comment]
this should not hold up the 0.9.0 release, so I move it to 0.9.5

**Comment by adcxyz** [comment]
@LFSaw ping

**Comment by adcxyz** [comment]
moving to sleeping beauties even though just pinged ;-)
