### ISSUE TITLE
enable/disable elements/groups at all levels

### ISSUE THREAD

**Issue by adcxyz** [ModalityTeam/Modality-toolkit#240]
There should be a simple interface to enable/disable MKtls and Elements at every level: 
single element, elementGroup, collective, other semantic group, entire MKtl. 
I would suggest 
MKtl(\x, ...)
// already implemented:
MKtl(\x).enable;   // en/disables responders
MKtl(\x).disable;
// these could just be with an <enabled flag in every element?
MKtl(\x).elementAt(\pad).disable;
MKtl(\x).elementAt(\pad, \1).enable;

**Comment by LFSaw** [comment]
wow. impressive. thanks!
