### ISSUE TITLE
update supercollider quarks for Modality

### ISSUE THREAD

**Issue by adcxyz** [ModalityTeam/Modality-toolkit#248]
I think SC should know about 3 Modality repos as Quarks: 

Modality-toolkit
ModalityWorkshop
ModalityTests

I guess we can drop Modality 3.4.4 compat?

Can someone with access to supercollider-quarks [Till, Miguel] please update?

**Comment by LFSaw** [comment]
done with https://github.com/supercollider-quarks/quarks/commit/53f94f751042da3b6c528941f56c086d0978387b

**Comment by adcxyz** [comment]
well that was quick, thanks!

**Comment by bhabbestad** [comment]
wow, guys, this is reaaly great work for a friday night!
its inspiring to see the progress :-)

and I wonder if we need to find a way to have another meeting to summarize
the changes and procedure, a best-practice-type situation, when 0.0 is ready and well.

tijs?

any news on the festival?
b.


16. okt. 2015 kl. 23:15 skrev Alberto de Campo <notifications@github.com>:
