### ISSUE TITLE
fix behringer BCF2000 BCR2000 re: new description design

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#249]
change description to reflect new style of semantics (hat switch etc.). 
See OP1 desc file for guidance.

( @miguel-negrao I assigned you because you have one at your fingers, right? )

**Comment by miguel-negrao** [comment]
I will have time to look at this and the other issue next week.

**Comment by miguel-negrao** [comment]
Do you mean search replace 'elementType' to 'type' ?

**Comment by LFSaw** [comment]
no, I mean turn it into a hierarchical description...

But Alberto redoes the description files anyhow so no need for this atm.

**Comment by adcxyz** [comment]
ok, went through that file, kept the naming as is. 
What is the new scheme this should adhere to?

**Comment by miguel-negrao** [comment]
I think these are now ok.
