### ISSUE TITLE
tutorial is outdated

### ISSUE THREAD

**Issue by miguel-negrao** [ModalityTeam/Modality-toolkit#252]
syntax and description files have changed.

**Comment by adcxyz** [comment]
Hi miguel, 
which one specifically? I updated the ModalityWorkshop/baseworkshop files in 4eba031, 
any others that you have found to be outdated?

**Comment by miguel-negrao** [comment]
The modality tutorial in the sc help files. From an email on the list:

On 20-11-2015 04:19, daniel palkowski wrote:
> However, in the tutorial, there was some code that is stumping me,
> namely their use of if( to get the dedicated play button on the nano to
> trigger the synth. The syntax is
>
> k.elements[\play].action_({  |el|
> if(el.value.booleanValue){
> x !? _.free;
> x = Synth(\blippy, [\freq, 440, \numHarmonics, 100, \amp, 0.5, \pan, 0])
> } {
> x !? _.free;
> x = nil;
> }
> )

Assuming you are running the latest version of Modality, then you have
probably made a copy paste error, you have a missing curly bracket at
the end, as the IDE would have pointed out by paiting that region red.
On the other hand the tutorial is somewhat outdated relative to the
latest code in master and the element names have changed. It should now be:

k.elements[\tr][\play].action_({  |el|
    if(el.value.booleanValue) {
        x !? _.free;
        x = Synth(\blippy, [\freq, 440, \numHarmonics, 100, \amp, 0.5,
\pan, 0])
    } {
        x !? _.free;
        x = nil;
    }
})

You can do k.gui and the activate trace in the gui to see the names of
each knob, button, etc.

The documentation should be updated at some point.

I don't know what is the canonical way to set values to a pbind, but
possibly one solution is to write to a bus and have the pbind read from
that bus ? Perhaps someone else from the Modality Team with patterns
experience can chime in ?
