### ISSUE TITLE
Have a default page

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#254]
For devices with pages, when mapping controls (using elementAt) it may be useful to have a default page (e.g. 0), this would make it easier to transfer code between devices that have different pages, and ones that don't.

**Comment by adcxyz** [comment]
You can do exactly that by making a separate MKtlDesc and MKtl for every page;
then the single page is maps directly to the non-paged device.
See PagedMKtl.schelp

**Comment by sensestage** [comment]
Does that also work with hardware pages easily?
Is there a simple way to say: make an MKtlDesc from this hardware page that is found in the description file?

(note, I still didn't have chance to look at the code again; the question/idea came up during our Creative Music Coding lab here).

**Comment by adcxyz** [comment]
> On 08/12/2015, at 21:57 , sensestage <notifications@github.com> wrote:
> 
> Does that also work with hardware pages easily?
> Is there a simple way to say: make an MKtlDesc from this hardware page that is found in the description file?

There are currently five devices that have hardware pages:

[
"behringer-bcf2000.desc.scd",
"behringer-bcr2000.desc.scd",
"qunexus/keith-mcmillen-qunexus.parentDesc.scd",
"korg-nanokontrol.desc.scd",
"novation-launchcontrol-xl.desc.scd”
]

Of these, the qunexus is alreay split into 4 files. 
The others are not - all of them have some elements that are in pages and others that are not.
I doubt that a single method or script would easily work for all of them; 
so it seems better to split each desc into pages correctly once by hand. 

> (note, I still didn't have chance to look at the code again; the question/idea came up during our Creative Music Coding lab here).

well it is the season for wishlists.

**Comment by adcxyz** [comment]
Actually, the initial request would now possible: 
you can add all elements of the desired page with .addNamed, 
then they are accessible directly without the scene number. 
But currently the hierarchies of elements and pages are different between descs; 
will put this in a separate issue.

**Comment by adcxyz** [comment]
Possible now, see
"Tutorials/Using_Hardware_Pages".openHelpFile
