### ISSUE TITLE
discourage use of \noteOnOff

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#256]
based on #251 + the possibility to get to the same of not caring for on/off 

```
// differentiate between noteOn and noteOff
MKtl(\op1).elAt(\key, 0, \on).action = {}
MKtl(\op1).elAt(\key, 0, \off).action = {}

// one action for both
MKtl(\op1).elAt(\key, 0).action = {}
```
and the potential (and actual happening) confusion arising from ```\noteOnOff``` as a ```\midiMsgType```, propose to dis-encourage and eventually deprecate/remove ```noteOnOff```.

**Comment by adcxyz** [comment]
+ 1

**Comment by adcxyz** [comment]
A downside to moving completely to [\noteOn, \noteOff]: 
There is no longer a single element with the state of on/off, 
as these are then separate elements. 
For midi buttons, this means that the \noteOn element is always 1,
and the noteOff element is always 0. 
Asking the group that has the two elements for its value
 returns the last velocity values of both on and off, e.g.:
k.elAt(\pkey, 0).value;something like [0.765, 0]; // 

So I added a new method to check whether on or off happened last, 
thus allowing to infer something like the on/off state:
k.elAt(\pkey, 0).isOn;

**Comment by adcxyz** [comment]
For the todo-list, 
I just checked, currently 22 of 44 device descs still use noteOnOff:
MKtlDesc.allDescs.select { |d| d.protocol == \midi }.size;

z = MKtlDesc.allDescs.select { |d| d.elementsDict.any { |el| el[\midiMsgType] == \noteOnOff } }.keys(Array).sort.postcs;
z.size;

**Comment by adcxyz** [comment]
down to 20 now.

**Comment by LFSaw** [comment]
@adcxyz and myself solved the noteOnOff issue with the following syntax that creates a noteOn/noteOff pair from within the MKtlDesc ( starting with ae26336b9ca335fd215d554828ac22adc7ceb3b0 ) :

```
MKtlDesc.notePair(
	(i+1).asSymbol, midiNote,
	style: (
		row: 7 - (i div: 8),
		column: i % 8,
		showLabel: true
	)
)
```

you can find a working example on how to use it in 
https://github.com/ModalityTeam/Modality-toolkit/blob/master/Modality/MKtlDescriptions/akai-lpd8.desc.scd


The GUI solution is a temporary one, leaving issue #77 in place.

**Comment by LFSaw** [comment]
ah, we will close this issue, once all the descriptions are transferred to the new syntax.

**Comment by adcxyz** [comment]
and there are now about ten of those left …

**Comment by adcxyz** [comment]
done now, so we can close this.

**Comment by LFSaw** [comment]
yey!
