### ISSUE TITLE
Traktor Kontrol z2 GUI problems

### ISSUE THREAD

**Issue by tapage** [ModalityTeam/Modality-toolkit#261]
Hi all

I'm having problems with the Gui of the Traktor Kontrol Z2
I manage to open the device and create a gui
but the gui looks thin and not all elements fit on the screen
then when I use some of the elements of the gui I get this error message:

```
ERROR: Message 'control' not understood.
RECEIVER:
   nil
ARGS:
   Integer 3
   Integer 31
   Float 127.000000   00000000 405FC000
CALL STACK:
    DoesNotUnderstandError:reportError   0x10abecbb8
        arg this = <instance of DoesNotUnderstandError>
    Nil:handleError   0x10abec428
        arg this = nil
        arg error = <instance of DoesNotUnderstandError>
    Thread:handleError   0x10abec6e8
        arg this = <instance of Thread>
        arg error = <instance of DoesNotUnderstandError>
    Object:throw   0x10abecb08
        arg this = <instance of DoesNotUnderstandError>
    Object:doesNotUnderstand   0x10abebf58
        arg this = nil
        arg selector = 'control'
        arg args = [*3]
    MIDIMKtlDevice:send   0x108e20878
        arg this = <instance of MIDIMKtlDevice>
        arg key = 'xsl'
        arg val = 127
        var elem = <instance of MKtlElement>
        var elemDesc = <instance of Event>
        var msgType = 'cc'
        var chan = 3
        var num = 31
    MKtl:send   0x10abebd48
        arg this = <instance of MKtl>
        arg key = 'xsl'
        arg val = 127
    MAbstractElement:trySend   0x10abebbe8
        arg this = <instance of MKtlElement>
    MKtlElement:valueAction_   0x10abeb2f8
        arg this = <instance of MKtlElement>
        arg newval = 1
    < FunctionDef in Method MKtlElementView:makeGetValueFunc >   0x10abeb718
        arg vw = <instance of Slider>
    View:doAction   0x10abeb7c8
        arg this = <instance of Slider>
^^ The preceding error dump is for ERROR: Message 'control' not understood.
RECEIVER: nil
```

Not sure how the Gui stuff works so I can't fix it...
All the rest of it works like a charm!

Best,
Tijs

**Comment by adcxyz** [comment]
fixed the error by catching missing midiout condition in 7546d99.
I added gui info to about a third of the controller elements I could identify, 
tijs will finish this shortly. 

todo: 
* check that midiout for other devices is built and works correctly
* in traktor desc file, maybe considered a hierarchy of elements.
As an example (I dont know which ones are midified, and which order makes most sense):
LL 
  kn 
    tone, macro, fx    
  bt 
    ON, C, A, 1, 2, 3, 4, Flux
  enc
L
  kn 
    gain, hi, mid, low, filter
  sl 
M 
  browse
  ...
R 
  kn 
    gain, hi, mid, low, filter
  sl 
RR
  kn 
    tone, macro, fx    // dont know which ones are midified and which not
  bt 
    ON, C, A, 1, 2, 3, 4, Flux
  enc

**Comment by adcxyz** [comment]
@tapage - ping .... 
is this issue still worth keeping open?

**Comment by LFSaw** [comment]
closed due to unresponsiveness of initiator. Added to https://github.com/ModalityTeam/Modality-toolkit/projects/1
