### ISSUE TITLE
Automate multiindex

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#262]
Icon I-Controls has these devices upon ```MKtl.find```:

```
MKtl('hid_0_icon_i', 'hid_0_icon_icontrols_v2_00');
		// [ "iCON iControls V2.00", "iCON", "09101" ]
		// no matching desc files found!

MKtl('midi_3_icon_icontrols_v2_00_port_1', 'midi_3_icon_icontrols_v2_00_port_1');
		// [ "iCON iControls V2.00", "iCON iControls V2.00 MIDI 1", 1310720 ]
		// create from desc file:
MKtl('midi_3_icon_icontrols_v2_00_port_1', "icon-icontrols");

MKtl('midi_4_icon_icontrols_v2_00_port_2', 'midi_4_icon_icontrols_v2_00_port_2');
		// [ "iCON iControls V2.00", "iCON iControls V2.00 MIDI 2", 1310721 ]
		// create from desc file:
MKtl('midi_4_icon_icontrols_v2_00_port_2', "icon-icontrols");
```

Doing this:
```m = MKtl('midi_3_icon_icontrols_v2_00_port_1', "icon-icontrols");```

outputs:

```
Meta_MKtlDevice:open: multiple device candidates found, please disambiguate by providing a multiIndex!
The candidates are:
( 'idInfo': ( 'destPortIndex': 0, 'deviceName': "iCON iControls V2.00" ), 'destDevice': MIDIEndPoint("iCON iControls V2.00", "iCON iControls V2.00 MIDI 1", 1310720), 'protocol': 'midi', 'filenames': [ "icon-icontrols" ], 
  'multiIndex': 0, 'deviceName': "iCON iControls V2.00", 'descs': [  ], 'lookupName': 'midi_3_icon_icontrols_v2_00_port_1', 'filename': "icon-icontrols", 
  'deviceInfo': MIDIEndPoint("iCON iControls V2.00", "iCON iControls V2.00 MIDI 1", 1310720) )
( 'idInfo': ( 'sourcePortIndex': 1, 'deviceName': "iCON iControls V2.00" ), 'protocol': 'midi', 'multiIndex': 1, 'filenames': [ "icon-icontrols" ], 
  'srcDevice': MIDIEndPoint("iCON iControls V2.00", "iCON iControls V2.00 MIDI 2", 1310721), 'deviceName': "iCON iControls V2.00", 'descs': [  ], 'lookupName': 'midi_4_icon_icontrols_v2_00_port_2', 'filename': "icon-icontrols", 
  'deviceInfo': MIDIEndPoint("iCON iControls V2.00", "iCON iControls V2.00 MIDI 2", 1310721) )
MKtl('midi_3_icon_icontrols_v2_00_port_1').openDevice: remaining virtual.
-> MKtl('midi_3_icon_icontrols_v2_00_port_1')
```

Shouldn't Modality be able to infer that there are multiple ports and provide the proper index in the printout?

**Comment by LFSaw** [comment]
it is not possible to understand how many of the devices are connected. Especially if the number of in and output devices is not the same for any device, proper derivation of the "right" port for a specific part of the device is rather difficult and prone to errors. We decided (for now) to keep the (easy) process of selecting the right index to the user.

**Comment by adcxyz** [comment]
multiIndex is for multiple items of the same device, and they are printed properly now.

port numbers are a separate issue: 
they are supported by making separate descs for every combination of 1 in 1 out port. 

So for the MIDI icontrols, there should be two desc files: 
icon-icontrols_port1.desc.scd, which should say 
(
...
idInfo: ("iCON iControls V2.00", sourcePortIndex: 0, destPortIndex: 0);
...
and the elements that talk thru port 1
...
)

and 
con-icontrols_port2.desc.scd, which should say 
(
...
idInfo: ("iCON iControls V2.00", sourcePortIndex: 1, destPortIndex: 1);
...
and the elements that talk thru port 2
...
)
I have no idea which are where, so someone with an iControls should do that.

**Comment by sensestage** [comment]
All I was suggesting really is, instead of outputting this on MKtl.find:

```
MKtl('midi_3_icon_icontrols_v2_00_port_1', 'midi_3_icon_icontrols_v2_00_port_1');
        // [ "iCON iControls V2.00", "iCON iControls V2.00 MIDI 1", 1310720 ]
        // create from desc file:
MKtl('midi_3_icon_icontrols_v2_00_port_1', "icon-icontrols");

MKtl('midi_4_icon_icontrols_v2_00_port_2', 'midi_4_icon_icontrols_v2_00_port_2');
        // [ "iCON iControls V2.00", "iCON iControls V2.00 MIDI 2", 1310721 ]
        // create from desc file:
MKtl('midi_4_icon_icontrols_v2_00_port_2', "icon-icontrols");
```

this:

```
MKtl('midi_3_icon_icontrols_v2_00_port_1', 'midi_3_icon_icontrols_v2_00_port_1');
        // [ "iCON iControls V2.00", "iCON iControls V2.00 MIDI 1", 1310720 ]
        // create from desc file:
MKtl('midi_3_icon_icontrols_v2_00_port_1', "icon-icontrols", multiIndex: 0);

MKtl('midi_4_icon_icontrols_v2_00_port_2', 'midi_4_icon_icontrols_v2_00_port_2');
        // [ "iCON iControls V2.00", "iCON iControls V2.00 MIDI 2", 1310721 ]
        // create from desc file:
MKtl('midi_4_icon_icontrols_v2_00_port_2', "icon-icontrols", multiIndex: 1);
```

So that if a device is found which has multiple ports, output example code that allows you to open the device with that port, without having to read through an error message.

This is before any desc-file is made.

**Comment by sensestage** [comment]
So it is still kept for the user, she just has easier code to copy and paste.

**Comment by adcxyz** [comment]
> On 26/03/2016, at 11:24 , sensestage <notifications@github.com> wrote:
> 
> All I was suggesting really is, instead of outputting this on MKtl.find:
> 
> MKtl('midi_3_icon_icontrols_v2_00_port_1', 'midi_3_icon_icontrols_v2_00_port_1');
>         // [ "iCON iControls V2.00", "iCON iControls V2.00 MIDI 1", 1310720 ]
>         // create from desc file:
> MKtl('midi_3_icon_icontrols_v2_00_port_1', "icon-icontrols");
> 
> MKtl('midi_4_icon_icontrols_v2_00_port_2', 'midi_4_icon_icontrols_v2_00_port_2');
>         // [ "iCON iControls V2.00", "iCON iControls V2.00 MIDI 2", 1310721 ]
>         // create from desc file:
> MKtl('midi_4_icon_icontrols_v2_00_port_2', "icon-icontrols");
> 
> this:
> 
> MKtl('midi_3_icon_icontrols_v2_00_port_1', 'midi_3_icon_icontrols_v2_00_port_1');
>         // [ "iCON iControls V2.00", "iCON iControls V2.00 MIDI 1", 1310720 ]
>         // create from desc file:
> MKtl('midi_3_icon_icontrols_v2_00_port_1', "icon-icontrols", multiIndex: 0);
> 
> MKtl('midi_4_icon_icontrols_v2_00_port_2', 'midi_4_icon_icontrols_v2_00_port_2');
>         // [ "iCON iControls V2.00", "iCON iControls V2.00 MIDI 2", 1310721 ]
>         // create from desc file:
> MKtl('midi_4_icon_icontrols_v2_00_port_2', "icon-icontrols", multiIndex: 1);
> 
> So that if a device is found which has multiple ports, output example code that allows you to open the device with that port, without having to read through an error message.

All I was saying is there is a misconception here: 
MIDI Devices with multiple ports need usually send different messages on each port, 
which should be in different descs. 

so instead of a single MKtlDesc(“icon-icontrols”);
 there should be two: 
MKtlDesc(“icon-icontrols-port1”);
which should have idInfo: (…, srcPortIndex: 0, destPortIndex: 0);
and:
MKtlDesc(“icon-icontrols-port2”);
which should have idInfo: (…, srcPortIndex: 1, destPortIndex: 1);

and then MKtl finds the right desc for the each port.

**Comment by adcxyz** [comment]
Sorry, that sounded unfriendly …
 
> All I was saying is there is a misconception here: 
> MIDI Devices with multiple ports need usually send different messages on each port, 
> which should be in different descs. 
> 
> so instead of a single MKtlDesc(“icon-icontrols”);
> there should be two: 
> MKtlDesc(“icon-icontrols-port1”);
> which should have idInfo: (…, srcPortIndex: 0, destPortIndex: 0);
> and:
> MKtlDesc(“icon-icontrols-port2”);
> which should have idInfo: (…, srcPortIndex: 1, destPortIndex: 1);
> 
> and then MKtl finds the right desc for the each port. 
> 

I assume the icontrols talks midi on port 1 mainly, yes? 
I just added idInfo with port indices to icon-icontrols, 
and comments for clarity. 
Does it do anything on port 2? 

@nescivi, please test that it shows up correctly now!
it should say now: 

MKtl('midi_3_icon_icontrols_v2_00_port_1', 'midi_3_icon_icontrols_v2_00_port_1');
       // [ "iCON iControls V2.00", "iCON iControls V2.00 MIDI 1", 1310720 ]
       // create from desc file:
MKtl('midi_3_icon_icontrols_v2_00_port_1', "icon-icontrols”);

MKtl('midi_4_icon_icontrols_v2_00_port_2', 'midi_4_icon_icontrols_v2_00_port_2');
       // [ "iCON iControls V2.00", "iCON iControls V2.00 MIDI 2", 1310721 ]
 	// something about no matching desc file found.

Tested again with 2 gamepads, multiIndex posting is not working properly yet, 
will look into it.

**Comment by adcxyz** [comment]
Fixed multiIndex posting - should also work for midi I think. 

With two Saitek Gamepads I now get as post:
```
// Available HIDMKtlDevices:
// MKtl('myNickName', 'lookupName');
		// [ product, vendor, (serial#) ]

MKtl('hid_5_usb_ga', 'hid_5_usb_game_controllers');
		// [ "USB Game Controllers", "Mega World" ]
		// create from desc file:
MKtl('hid_5_usb_ga', "saitek-impact-gamepad", multiIndex: 0);

MKtl('hid_6_usb_ga', 'hid_6_usb_game_controllers');
		// [ "USB Game Controllers", "Mega World" ]
		// create from desc file:
MKtl('hid_6_usb_ga', "saitek-impact-gamepad", multiIndex: 1);
```
and all 4 code lines work for creating an MKtl.
