### ISSUE TITLE
Actions not reset when freeing a MKtl

### ISSUE THREAD

**Issue by patrickdupuis** [ModalityTeam/Modality-toolkit#270]
example:
```

k = MKtl('nk2', "*nanokontrol2");

k.elAt(\sl, 0).action = { arg el; el.value.postln;};

k.gui;

// move slider 1, values posted

k.resetActions;

// move slider 1, no values posted

k.elAt(\sl, 0).action = { arg el; el.value.postln;};

k.free;

// move slider 1, values posted
```
Is this a bug, or do users need to resetActions before freeing a device? I tried replacing k.free with k.closeDevice and got the same result. 

I'm on linux and SC 3.7.2.

Cheers,
Patrick

**Comment by adcxyz** [comment]
closed with merge 3a6e7f8

**Comment by patrickdupuis** [comment]
This problem is still present after commit 3a6e7f8.

**Comment by patrickdupuis** [comment]
There is nothing for .resetActions to do if the elementsDict is already nil. The .free method should read as follows, right?

```
free {
        this.closeDevice;
		elementGroup = elementsDict = nil;
		all.removeAt( name );

}
```

**Comment by patrickdupuis** [comment]
It appears the problem is in the closeDevice method. I tried posting a message after the if statement, and it didn't post. That means the device.isNil is testing True. this.resetActions never gets called.

**Comment by adcxyz** [comment]
done ok now, tests above show no action after k.free.
