### ISSUE TITLE
update ABNF form im MKtl_description_files

### ISSUE THREAD

**Issue by adcxyz** [ModalityTeam/Modality-toolkit#276]
MKtl_description_files has a definition of the description file format in ABNF form. 
This should be updated to the current desc file format. 

https://github.com/ModalityTeam/Modality-toolkit/blob/master/Modality/HelpSource/Reference/MKtl_description_files.schelp

**Comment by LFSaw** [comment]
what is ABNF? Why do we need it here? I'd vote for removing it. I never looked at it, did anyone?

**Comment by LFSaw** [comment]
I remeber @miguel-negrao working that one out... maybe he can comment?

**Comment by miguel-negrao** [comment]
[ABNF](https://en.wikipedia.org/wiki/Augmented_Backus%E2%80%93Naur_form) is a standard formal definition of a language. It allows to specify with precision text which is considered correct according to a certain language. In our case, it allows to specify what is a a correct definition file.

**Comment by miguel-negrao** [comment]
It might be too much trouble to keep it up to date. Perhaps better to delete it and just use a more ad-hoc method of specifying the syntax.
