### ISSUE TITLE
check / update FRP and Push-lightshow examples

### ISSUE THREAD

**Issue by adcxyz** [ModalityTeam/Modality-toolkit#277]
Moving these here, so we can close the Big Examples issue #175 

@miguel-negrao - can you please check the two FRP examples? they are
https://github.com/ModalityTeam/ModalityWorkshop/blob/master/cookbook/complex-copy-paste/complex-copy-paste_frp_style.scd
https://github.com/ModalityTeam/ModalityWorkshop/blob/master/cookbook/switchingActions/switchActionsFRP.scd
@LFSaw - can you please check this one:
https://github.com/ModalityTeam/ModalityWorkshop/tree/master/cookbook/lightshow

**Comment by miguel-negrao** [comment]
complex-copy-paste_frp_style.scd is okay.
updated switchActionsFRP.scd.

**Comment by adcxyz** [comment]
IIUC, this is done, so closing. thanks @miguel-negrao !
