### ISSUE TITLE
Different Versions of MKtlDesc.sc in sc-quarks + github

### ISSUE THREAD

**Issue by monodread** [ModalityTeam/Modality-toolkit#284]
My SuperCollider (3.8) generated problems loading an MKtl with a custom description. Upon looking into this it turns out that the MKtlDesc File of my quark is different than the one up here on the github master branch. There seem to have been changes in the past how a desc file needs to be written? I used \elementsDesc whereas in the other version \description is used. Also the method *filenameForIDInfo is different, in the other MKtlDesc this is *filenamesForIDInfo. Which is the current / latest version? Perhaps it is that the quark is out of date - but can the Quarks class recognize such an issue?? 
thanks - jonas
PS: adding to the problematic is that: if I throw out the quark and symlink to this repo, then SC will still load the helpfiles from the quark. meaning I will only see descriptions of the old, faulty methods and not for the actual MKtl classes I am using...

This is what the quarks gui says. apparently it links to Miguel's repo instead of the master?
http://i65.tinypic.com/es0ztt.png

**Comment by LFSaw** [comment]
@monodread , just only now seeing this. My Quarks dir links to this repository, so it should be fine.
To answer your question: yes, there were major changes in the recent months, the currently "true" version is in this repository.

**Comment by LFSaw** [comment]
closed because stale and question answered.
