### ISSUE TITLE
Launchcontrol pads not working properly

### ISSUE THREAD

**Issue by kflak** [ModalityTeam/Modality-toolkit#285]
I’m having a bit of difficulty getting data from Launchcontrol pads using the Modality toolkit. The nav buttons all work fine, as do the knobs. However, when pressing the pads I get the message:

MKtl('lc') : unknown 'noteOn' element found at midiNum: 9,  midiChan 0.
	Please add it to the description file. E.g. for a button:<bt>: (midiMsgType: 'noteOn', elementType: <'button'>, midiChan: 0, midiNum: 9, spec: <'midiBut'>, mode: <'push'>)

MKtl('lc') : unknown 'noteOff' element found at midiNum: 9,  midiChan 0.
	Please add it to the description file. E.g. for a button:<bt>: (midiMsgType: 'noteOff', elementType: <'button'>, midiChan: 0, midiNum: 9, spec: <'midiBut'>, mode: <'push'>)

This seems a bit strange, as the desc file contains the lines:

				(
					key: \bt,
					shared: ('elementType': 'pad', 'spec': 'midiNote', \ioType: \inout),
					elements: ((9..12) ++ (25..28)).collect{|num, i|
						(
							key: (i+1).asSymbol, midiNum: num,
							groupType: \noteOnOffBut,
							shared: (
								style: ( row: 2, column: i )
							)
						)
					}

				),

which, if I’m not mistaken, seems to address that specific issue. Am I missing something basic here? I’m a complete newbie to the world of MKtl…

Best,
K

**Comment by kflak** [comment]
This is happening on SC 3.8, Mac OSX 10.11.6

**Comment by adcxyz** [comment]
hi kenneth, 
in the desc file, try adding the groupType to shared as well, as below, 
then recompile, 
try if it works then and report back. 
best 
adc
```
				(
					key: \bt,
					shared: ('elementType': 'pad', 'spec': 'midiNote', \ioType: \inout),
					elements: ((9..12) ++ (25..28)).collect{|num, i|
						(
							key: (i+1).asSymbol,
							groupType: \noteOnOffBut,
							shared: (
								 // added here: 
								groupType: \noteOnOffBut,
								midiNum: num,
								style: ( row: 2, column: i )
							)
						)
					}

				),
```

**Comment by kflak** [comment]
Works! Thanks a lot!
