### ISSUE TITLE
Where is \padUp defined for \noteOnOff

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#291]
It might be more logical if it is a pianoKey type, that then the noteOff gets the type \pianoKeyUp instead of \padUp.

**Comment by sensestage** [comment]
seems to be in MKtlDesc:initGroupFuncs

**Comment by LFSaw** [comment]
@adcxyz ?

**Comment by sensestage** [comment]
I guess this is also interlinked with the GUI representations.

**Comment by tiagmoraismorgado** [comment]
I agree, with the naming terminonology

**Comment by adcxyz** [comment]
Yes, it is used in MKtlGUI, as devised by wouter: 

\pianoKey redirects to \pad, which creates an MPadView.
Should someone add a PianoKeyView, it would be easy to point \pianoKey to that.
Very likely, that would be a different-looking subclass of MPadView.

\padUp creates a MPadUpViewRedirect which is virtual only, 
and actually talks to the MPadView the pianoKey has created. 

Sure, one can add \pianoKeyUp and redirect it to \padUp, 
to make the representation more semantic. 

Yes, the defaults for this happen in MKtlDesc:initGroupFuncs, 
in the various noteOnOff behaviors - which actually only worry about the midi details, 
not the visual representation. 
So, after creating such a group of  [noteOn, noteOff, <touch>], there could be a method like 
improveElementTypes, which replaces them based in the elementType in the shared dict.

**Comment by adcxyz** [comment]
question is answered, so closing.
