### ISSUE TITLE
MKtlDesc.addFolder should also accept that the folder MKtlDescriptions is already made

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#292]
if the folder already is named MKtlDescriptions, it should not try to add it again.

e.g. `MKtlDesc.addFolder ( "~/Desktop/MKtlDescriptions" );` should just work.

It is confusing that if you pass a valid folder that it does not find it and is actually looking for:
`"~/Desktop/MKtlDescriptions/MKtlDescriptions"`

**Comment by adcxyz** [comment]
Why not just use the both path and name arguments that addFolder currently asks for?
you can let the name default to the recommended folderName, 
and save precious typing time ;-)

**Comment by LFSaw** [comment]
What is the status on this? I don't understand the problems here...

**Comment by adcxyz** [comment]
> What is the status on this? I don't understand the problems here...

I don't really see a problem. 
The method supplies "MKtlDescriptions" as default folder name, thus nudging users to use that name. I don't know why it should also allow typing that out by hand, requiring extra just-in-case logic for it.

The most sensible option is to use ```MKtlDesc.userFolder``` for all special/customized/personal desc files, keep them there, and never worry.

@sensestage, is this answered?

**Comment by adcxyz** [comment]
@sensestage ping ...

**Comment by adcxyz** [comment]
no response, so closing.
