### ISSUE TITLE
groupType: \noteOnOff does not propagate spec properly

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#296]
A noteOnOff defined as:
```
specs: (
	magButton: [0,100,\linear,1].asSpec;
),

(
	key: \bt,
	shared: (
		groupType: \noteOnOff, midiNum: item,spec: 'magButton',
		style: ( row: (i/5).floor + 4, column: i%5, height: 1 )
	)
)
```

results in:
```
// elemDesc for on
-> ( 'midiMsgType': noteOn, 'spec': midiVel, 'style': ( 'column': 2, 'height': 1, 'row': 4 ), 'elemKey': bt_1_2_on, 
  'key': on )
// elemDesc for off
-> ( 'spec': midiBut, 'elemKey': bt_1_2_off, 'midiMsgType': noteOff, 'key': off, 
  'style': ( 'column': 2, 'height': 1, 'row': 4 ), 'elementType': padUp )
```

I think we should also rethink cases where noteOff actually has a velocity that is non-zero.

**Comment by LFSaw** [comment]
I understand the bug, what does 

> I think we should also rethink cases where noteOff actually has a velocity that is non-zero.

mean? how does it relate to the issue?

**Comment by sensestage** [comment]
It has to do with the general way of handling noteOn and noteOffs - maybe not directly with the issue, but more a general discussion.

With the current behaviour a noteOff with velocity 100 does not turn off the element value of the group.
This was a case with a custom built device, where it was just programmed to have that velocity.

**Comment by LFSaw** [comment]
added #299 to reflect this behaviour.

**Comment by adcxyz** [comment]
@sensestage - Have you tried it with \noteOnOffVel ? 
I dont have any devices with off velocity, so I cant test. 

Generally, the problem is in MIDI - when separate messages set the same state, (on/off),
the state can become ambiguous when a single message is dropped (hanging notes.)

Currently, it should work like this: 
```
(
d = (
deviceName: "nord drum2",
protocol: 'midi', deviceType: 'drum',
elementTypes: [ \pad, \knob ],
idInfo: "EXTERNAL",

elementsDesc: (
	 elements: [
		(
			key: \pad,
			shared: (\elementType: \pad, groupType: \noteOnOffVel,
				\midiChan: 9, \spec: \midiVel, \ioType: \inout
			),
			elements: [
				(key: '1', midiNum: 60, shared: (style: (row: 0, column: 0))),
				(key: '2', midiNum: 62, shared: (style: (row: 0, column: 1))),
				(key: '3', midiNum: 64, shared: (style: (row: 0, column: 2))),
				(key: '4', midiNum: 65, shared: (style: (row: 1, column: 0))),
				(key: '5', midiNum: 67, shared: (style: (row: 1, column: 1))),
				(key: '6', midiNum: 69, shared: (style: (row: 1, column: 2))),
			]
		),

	]
)
);
)
m.free; m = MKtl( \ndr, d );
m.trace.gui;
// both values, no way to tell what happened last...
m.elAt(\pad, \1).value; 
// ... but you can ask the group whether on or off happened last:
m.elAt(\pad, \1).isOn;  
```
Maybe a good solution is to create a single element that goes from +127 (noteOn) to -127 (max noteOff)? 
Until there is an implementation of that (or a better idea), the above should work.

**Comment by adcxyz** [comment]
... and here is an example for that:
```
m.addSpec(\bivel, [-127, 127]);

m.addNamed(\biVel, MKtlElementGroup(\biVel, m, 
	m.elAt(\pad).collect { |grp, i|
		MKtlElement((i+1).asSymbol, (spec: \bivel), m);
	}
));

m.elAt(\biVel).action = { |el| [\bivel, el.name, el.deviceValue].postcs };

// test biVel behaviour directly:
// noteOn
m.elAt(\biVel, 0).deviceValueAction = 127; 
// noteOff
m.elAt(\biVel, 0).deviceValueAction = 0; 
// noteOff neg vel
m.elAt(\biVel, 0).deviceValueAction = -64;

// tell pads to inform bivel: 
m.elAt(\pad).action = { |el, i| 
	var sign = if (el.keyInGroup == \on, 1, -1);
	var bivel = m.elAt(\biVel, el.indexInGroup);
	bivel.deviceValueAction = el.deviceValue * sign;
	el.name.postcs;
};

// test as incoming from midi:
m.elAt(\pad, \1, \on).deviceValueAction_(64);
m.elAt(\pad, \1, \off).deviceValueAction_(64);
```

**Comment by adcxyz** [comment]
@sensestage, does the above clear up the issue, and let you write a working desc file?
I just added a tutorial about groupTypes in 0193efa.

To explain generally, groupTypes like noteOnOff are shorthands that *create* the proper specs for buttons, so you don't need to spell them out everywhere (just assume 0-127 midi). 
noteOnOff is defined to create noteOn with midiVel, and noteOff without midiBut, as this is the most common case.
 
Probably specs given by hand should override these ? That does raise questions though - in your example case, does the magButton spec apply to both  noteOn and noteOff? Does every noteOff message have a value of 100? 

Generally, when devices have strange specialties, it may make more sense to make their elements by hand, and not add layers of complexity to override details of the shorthands (which would become really hard to reason about).
2c adc

**Comment by adcxyz** [comment]
@sensestage - ping

**Comment by adcxyz** [comment]
@sensestage - ping ping

**Comment by adcxyz** [comment]
no response, so I consider this answered.
