### ISSUE TITLE
MKtlDesc should have a method to reread the file

### ISSUE THREAD

**Issue by sensestage** [ModalityTeam/Modality-toolkit#297]
It seems at the moment there is no way to force MKtlDesc to reread a desc file.
This is useful when creating and editing a descfile and using MKtl.rebuild to rebuild the device.

**Comment by LFSaw** [comment]
@adcxyz I thought this is possible already, do you recall?

**Comment by sensestage** [comment]
as far as I could you you could rebuild with a different file, but not the same file that has changed in the meantime.
