### ISSUE TITLE
A `noteOff` with e.g. velocity 100 does not turn off the element value of its group.

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#299]
Examples where this is needed are: 

+ a custom-built device, where it was just programmed to have that velocity. ( @sensestage  )
+ OP-1

**Comment by adcxyz** [comment]
I think this is a misunderstanding, not a bug. 
with a noteOnOff group, there is no single group value, but separate values for \on and \off, 
which separately keep the latest value of noteOn velocity and of noteOff velocity that came in.
The group has an isOn method to check which type of message happened last, so one can infer the likely mechanical state of the physical element it came from.

**Comment by LFSaw** [comment]
@sensestage ?

**Comment by LFSaw** [comment]
I think I understand the inner workings of this. So I do not consider this a bug.

**Comment by adcxyz** [comment]
@sensestage - ping :-)

**Comment by adcxyz** [comment]
is this still an issue even? IMHO it is not - maybe it should be added to the doc somewhere.
