### ISSUE TITLE
MKtlDesc - add user folder

### ISSUE THREAD

**Issue by adcxyz** [ModalityTeam/Modality-toolkit#303]
MKtlDesc is meant to support user specific descs. I would propose 
auto-creating a folder code::MKtlDescscriptions:: in code::Platform.userAppSupportDir::,
and advising users to place their custom desc files there.
When distributing custom descs to others, one can 
either place them in that user folder, 
or put them next to the file that needs the desc, 
and load it with something like:
code::MKtlDesc.fromFile("my-nanoktl2.desc.scd".resolveRelative);:

Opinions please :-)

**Comment by adcxyz** [comment]
false alarm, exists already. 
added it to a few more places in the help files in 2a0941b, and closing.

**Comment by LFSaw** [comment]
:)

**Comment by adcxyz** [comment]
oh well, memory used to be better ... i think
