### ISSUE TITLE
caught exception in primitive Meta_File

### ISSUE THREAD

**Issue by wtkns** [ModalityTeam/Modality-toolkit#309]
OSX 10.12.5, SC 3.8, I was testing my own quark file, which calls modality as a dependency.

Modality was working fine. I deleted my downloaded-quarks folder contents and sclang_conf.yaml file, recompiled and all was well.

After installing Modality-toolkit via Quarks.gui; compiling the class library gives me the following error.

However, using Quarks.gui and selecting the Modality-toolkit 2.1 version compiles as expected. I was also able to replicate this issue on another computer running OSX 10.11.

Thanks for any assistance!
+++

Fetching https://github.com/supercollider-quarks/quarks.git
Installing Modality-toolkit
Adding path: /Users/james/Library/Application Support/SuperCollider/downloaded-quarks/Modality-toolkit
Modality-toolkit installed
compiling class library...
initPassOne started
	NumPrimitives = 711
initPassOne done
	compiling dir: '/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary'
	compiling dir: '/Users/james/Library/Application Support/SuperCollider/Extensions'
	compiling dir: '/Users/james/Library/Application Support/SuperCollider/downloaded-quarks/Modality-toolkit'
	pass 1 done
	numentries = 1241677 / 19894312 = 0.062
	6014 method selectors, 3308 classes
	method table size 19837632 bytes, big table size 159154496
	Number of Symbols 15224
	Byte Code Size 458251
	compiled 492 files in 0.49 seconds

Info: 3 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
82
caught exception in primitive Meta_File:mtime
ERROR: boost::filesystem::last_write_time: No such file or directory: "/Users/james/Library/Application Support/SuperCollider/MKtlDescriptions/_allDescs.cache.scd"ERROR: Primitive '_FileMTime' failed.
Failed.
RECEIVER:
class File (0x10faa1240) {
  instance variables [19]
    name : Symbol 'File'
    nextclass : instance of Meta_FileDialog (0x10f467440, size=19, set=5)
    superclass : Symbol 'UnixFILE'
    subclasses : instance of Array (0x10ad48540, size=1, set=2)
    methods : instance of Array (0x10faa13c0, size=12, set=4)
    instVarNames : instance of SymbolArray (0x10faa1540, size=1, set=2)
    classVarNames : instance of SymbolArray (0x10faa16c0, size=2, set=2)
    iprototype : instance of Array (0x10faa1600, size=1, set=2)
    cprototype : instance of Array (0x10faa1780, size=2, set=2)
    constNames : nil
    constValues : nil
    instanceFormat : Integer 0
    instanceFlags : Integer 0
    classIndex : Integer 1592
    classFlags : Integer 0
    maxSubclassIndex : Integer 1593
    filenameSymbol : Symbol '/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Files/File.sc'
    charPos : Integer 0
    classVarIndex : Integer 198
}
CALL STACK:
	MethodError:reportError   0x10ad3f0b8
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError   0x10ad3f298
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError   0x10ad3f4b8
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw   0x10ad3f568
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed   0x10ad3fcd8
		arg this = <instance of Meta_File>
	< FunctionDef in Method Meta_MKtlDesc:checkCaches >   0x10ad25d18
		arg folder = "/Users/james/Library/Applica..."
		arg i = 1
		var files = [*0]
		var newestDescTime = nil
		var cacheTime = nil
	ArrayedCollection:do   0x10ad27108
		arg this = [*2]
		arg function = <instance of Function>
		var i = 1
	List:do   0x10ad271b8
		arg this = <instance of List>
		arg function = <instance of Function>
	Meta_MKtlDesc:checkCaches   0x10ad24fa8
		arg this = <instance of Meta_MKtlDesc>
		var cacheTime = nil
		var lastDescTime = nil
	Meta_MKtlDesc:initClass   0x10ad243e8
		arg this = <instance of Meta_MKtlDesc>
	Meta_Class:initClassTree   0x10ad21e68
		arg this = <instance of Meta_Class>
		arg aClass = <instance of Meta_MKtlDesc>
		var implementsInitClass = nil
	ArrayedCollection:do   0x10ad24ce8
		arg this = [*296]
		arg function = <instance of Function>
		var i = 9
	Meta_Class:initClassTree   0x10ad23ee8
		arg this = <instance of Meta_Class>
		arg aClass = <instance of Meta_Object>
		var implementsInitClass = nil
	Process:startup   0x10ad22f68
		arg this = <instance of Main>
		var time = 63.157281197
	Main:startup   0x10ad21708
		arg this = <instance of Main>
		var didWarnOverwrite = false
^^ The preceding error dump is for ERROR: Primitive '_FileMTime' failed.
Failed.
RECEIVER: File

**Comment by adcxyz** [comment]
Hi, 
that was my addition of checkCaches - please try again and tell me if it works now. 
best adc

**Comment by wtkns** [comment]
that seems to have done it. thanks for the speedy fix and all of the hard work!

**Comment by adcxyz** [comment]
:-)
