### ISSUE TITLE
Arturia BeatStep Stop Button

### ISSUE THREAD

**Issue by retroriff** [ModalityTeam/Modality-toolkit#331]
Hello,

I am not able to trigger an action when the stop button is pressed. I have read that MMC buttons are not being received and Notes are used instead. I can detect the play button with `MIDIdef.noteOn`, which default setting number is 60, and I also can detect knobs:

`m.elAt(\pg0, \kn, 0).action = { |el| ["Knob", el.value].postln;};`

Any suggestion?

**Comment by adcxyz** [comment]
fixed with #333
