### ISSUE TITLE
Pads not recognized

### ISSUE THREAD

**Issue by retroriff** [ModalityTeam/Modality-toolkit#332]
Hello,

on Artutia BetStep actions are not triggered when pads are pressed:

`m.elAt(\pg0, \pad).action = { |el| ["Pad", el.value].postln;};`

Trace says:

> MKtl('bs') : unknown 'noteOn' element found at midiNum: 44,  midiChan 0.
	Please add it to the description file. E.g. for a button:<bt>: (midiMsgType: 'noteOn', elementType: <'button'>, midiChan: 0, midiNum: 44, spec: <'midiBut'>, mode: <'push'>)

I am using Arturia factory default settings. Should I edit the description file to add my pad numbers?

Thank you

**Comment by adcxyz** [comment]
Hello, 
only saw this now, sorry for the long silence - 
it turns out that there is something broken in how multi-MIDI buttons/keys 
are expanded :-/ 
will look into a general fix soon, 
if you need a quick and dirty working version the beatstep earlier, 
let me know, I can send one.

**Comment by adcxyz** [comment]
fixed with #333
