### ISSUE TITLE
rebuild is broken ? 

### ISSUE THREAD

**Issue by madskjeldgaard** [ModalityTeam/Modality-toolkit#335]
Hello

Maybe I have misunderstood how to use the rebuild method but for me it simply does not work. I am on SC 3.10.4 / Ubuntu Studio 19 / SCNVim and using the latest version of Modality. 

```
c = MKtl('name', "*lpd8");
c.rebuild("*lpd8") // The preceding error dump is for ERROR: Message 'not' not understood.
```

**Comment by adcxyz** [comment]
Hi Mads, 
thanks for spotting that - only saw it now, was simple to fix.
