### ISSUE TITLE
Should future JSON desc files be notated flat or hierarchical?

### ISSUE THREAD

**Issue by adcxyz** [ModalityTeam/Modality-toolkit#43]
If flat, we need a way to go from JSON-flat back to sc-hierarchical;
If hierarchical - which seems better - we need a way to notate the hierarchy 
with just arrays and dicts.

**Comment by adcxyz** [comment]
Is this a goal for this week?
* script to render all description files into cross-platform readable JSON files

**Comment by LFSaw** [comment]
see #23
