### ISSUE TITLE
write desc-file to control RME totalmix

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#45]
Any of you would like to talk to the RME hardware?
here's the latest OSC table for controlling RME´s TotalMix FX.

http://www.rme-audio.de/forum/viewtopic.php?id=17232

**Comment by sensestage** [comment]
should be possible now

**Comment by LFSaw** [comment]
should go into the cookbook then.

**Comment by adcxyz** [comment]
started on this one with 068647b, hopefully this is clear enough so someone else can add all the other messages.

**Comment by LFSaw** [comment]
@bhabbestad ping

**Comment by adcxyz** [comment]
@bhabbestad ping

**Comment by adcxyz** [comment]
closing and moving to projects.
