### ISSUE TITLE
soft paging

### ISSUE THREAD

**Issue by miguel-negrao** [ModalityTeam/Modality-toolkit#48]
make a controller paged via software

FRP version:
https://github.com/miguel-negrao/FPLib/blob/master/Examples/FRP/soft%20paging.scd

**Comment by adcxyz** [comment]
new example for soft paging in cookbook:
https://github.com/ModalityTeam/ModalityWorkshop/blob/master/cookbook/soft_paging/paging_MKtls.scd
```
// Make 2 MKtls which point to the same device
MKtl('\ada', "korg-nanokontrol2");
MKtl('\bob', "korg-nanokontrol2");
// activate page 1 mktl
MKtl('\ada').enable; MKtl('\bob').disable;
// activate page 2 mktl
MKtl('\bob').enable; MKtl('\ada').disable;
```
could be built into a lightweight container class for multiple MKtls that does the switching and little else.
Please comment whether this is a good way to go!

**Comment by miguel-negrao** [comment]
For 2 pages it looks quite simple, nice ! For more pages, I guess some wrapping logic would be needed. What about resetting the control (GUI slider, motorized MIDI, OSC) on a page change ?

**Comment by adcxyz** [comment]
sure, resetting devices with output would make sense. 
A little class that handles multiple pages shoudl do that :-)

**Comment by adcxyz** [comment]
MKtl.enable now sync-sets values to device.

**Comment by adcxyz** [comment]
opinions please - is this good enough already for 0.9.0?
if so, we can close this one

**Comment by miguel-negrao** [comment]
sorry can't test at the moment, but from what you describe it seems like it has the needed functionality. I say you can close it.

**Comment by adcxyz** [comment]
ok, closed.
