### ISSUE TITLE
default deviceDescription files in quarks, custom ones in userAppSupportDir

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#66]

**Comment by adcxyz** [comment]
Proposal for this:
Refactor the descriptions out to a separate class MKtlDesc that handles all the folders, file lookups, 
 conversions between symbol for descname, string for descfilename, and the event that contains the full description as read from the desc file; then a lot of the if cascades in MKtl could go away.
I can make a sketch today.

**Comment by adcxyz** [comment]
done in the MKtl refactor branch.

**Comment by adcxyz** [comment]
now also in current master - it does read in that folder;
full test coming soon.

**Comment by adcxyz** [comment]
done now in refactor branch.

**Comment by LFSaw** [comment]
I am so happy about this!
