### ISSUE TITLE
Adding custom filter elements to an existing (and instantiated) controller

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#72]
````
m = MKtl.make(\meXYController, \meXYControl);
m.addVirtualElement(\xyPolar, {| me |
    atan2(me.elements[\x], me.elements[\y])
})
````
as suggested by @dhmlGIT

**Comment by LFSaw** [comment]
@adcxyz, you had an example for this somewhere?
Should go into the cookbook (and be referenced here...)

**Comment by adcxyz** [comment]
the example is in MKtlElement.schelp

**Comment by adcxyz** [comment]
and also in the cookbook : 
https://github.com/ModalityTeam/ModalityWorkshop/blob/master/cookbook/derived-elements/derived-elements-mfunc.scd
