### ISSUE TITLE
noteOn and noteOff as same GUI representation?

### ISSUE THREAD

**Issue by jcarey0000** [ModalityTeam/Modality-toolkit#77]
It would be visually handy to have the autoGUI associate noteOn/noteOff of the same midi note with the same slider.  The velocity could be displayed as the label when set by the noteOn?

**Comment by adcxyz** [comment]
I think the best option for the desc files is to always put them together: 
I went through all descs in the desc_reorg branch  to adapt them to the final style, 
and always notated noteOn noteOff as noteOnOff:
```
(
key: \pad,
shared: (\midiMsgType: \noteOnOff, \type: \key,
	\spec: \midiNote, \ioType: \in),
elements: (36..99).collect { |num|
	(midiNum: num)
}
)
```
and all thumbsticks are now :
```
(
key: \l,
elements: [
	(key: \x, 'hidUsage': 48, 'elementType': 'joyAxis', spec: \cent1,
		mode: \center, 'style': (row: 4, column: 1, showLabel: true)
	),
	(key: \y, 'hidUsage': 49, 'elementType': 'joyAxis', spec: \cent1,
		mode: \center, 'style': (row: 4, column: 2, showLabel: true)
	),
	(key: \hat, 'hidUsage': 11, 'elementType': 'button', 'hidUsagePage': 9,
		spec: \hidBut, mode: \push,
		'style': (row: 3.2, column: 1.5, showLabel: true)
	)
]
)
```
hope that is consistent enough for a gui representation.

**Comment by adcxyz** [comment]
Done.

Reversing the decision to drop \noteOnOff in #256, 
MKtlDesc now supports a number of keys for \groupType, which expand into small groups of elements, see MKtlDesc.help. some examples:
```
\noteOnOff ->  noteOn + vel 1-127, noteOff 0 
\noteOnOffBut -> noteOn vel 127, noteOff vel 0
\noteOnOffTouch -> noteOn + vel 1-127, noteOff 0, polytouch 1-127
...
```
These are mirrrored as modes in MPadView, where a single MPadView represents
up to 3 elements in a single view: 
```
MPadView.modeKeys;
-> [ noteOnLed, noteOnOff, noteOnOffBut, noteOnOffButCtl, 
noteOnOffCtl, noteOnOffTouch, noteOnOffVel, noteOnOffVelTouch, noteOnTrig, noteOnVel ]
```
For piano-like keyboard guis, the Piano class creates layout info, 
which can be used flexibly in the desc files. See Piano help file, and e.g. 
```
MKtl('apc', "akai-apcmini").gui;
```
