### ISSUE TITLE
MKtlElement should reflect toggle/snapback state of elements

### ISSUE THREAD

**Issue by LFSaw** [ModalityTeam/Modality-toolkit#90]
@sensestage noticed that the GUI replacement should take some note of the type of buttons. 
Right now the GUI interaction is that buttons are automatically toggles, whereas the user interaction with the real device could as well be push buttons. 
The GUI should reflect that, and not toggle the button between on and off, but instead give a momentary on-function, or even distinguish between mouse press on, and mouse press off time to reflect the interaction with the real device better.

We used to have a type where it said things like snapBack/toggle/...
but we got rid of it because it was not yet used...

```
// somewhere here
(\midiMsgType:
        \noteOnOff, \type: \button, \midiChan: 0, \midiNum: note, \spec:
        \midiVel)
```

**Comment by adcxyz** [comment]
OK, some more considerations about this one:
* naming: 
this actually concerns buttons and switches, so good names would be:
```
(elemType: \button, buttonMode: \toggle)  // default, so you can leave it out 
(elemType: \button, buttonMode: \momentary) // has to be specified
\toggle // is one click for on, next click off, and
\momentary // is mouseDown for on, mouseUp for off
```
-> All descs should have indications for momentary buttons, 
so their actions can be built accordingly automatically. 

Then there is difficulty for momentary GUI buttons: One can only hold down a single button at a time! But for really testing device behavior from a GUI, it is necessary to simulate holding down some buttons while pressing others, e.g. holding down bt_1 to shift the mode for buttons 2-8. 

Some options how to do that:
1.  Momentary GUI buttons can be alt-clicked to change state on mouseDown only, not on both
2. While holding a momentary GUI key down, you can type L to lock it to on state, 
   and the next click will just unlock it
3. Key shortcuts to switch a GUI button from toggle to momentary and back, e.g. $m -> momentary, $t -> toggle

For default GUI behavior, I would prefer the following:
* Make all GUI buttons toggles by default (as now), and 
* select a button and type $m to switch it to momentary mode, and
* when needed, switch back to toggle mode with $t. 

Opinions please!

**Comment by adcxyz** [comment]
The second half of this is missing of course:

For elements that physically return to a specific value (e.g. springed joyAxis), 
elementDescs should have a value for snapback called e.g. 
(snapbackValue: 0) that the element returns to on mouseUp when in momentary mode.
this means that sliders and/or knobs should have a momentary mode too; 
For full testing, here we also need to have a \hold mode to simulate holding the slider physically while doing something else.

**Comment by adcxyz** [comment]
```
// examples for switching on the fly between GUI momentary/snapback and toggle modes:
x = MKtl(\x, "*3d*");
g = MKtlGUI(mktl: x);
// x.desc.openFile;

// tell the three joystick axes to use snapback
g.views.keep(-3).do { |elView| 
	elView.snapbackValue_(0.5);
	elView.snapback_(true);
};

// give knob a weird snapbackvalue
g.views[0].snapbackValue_(0.314159).snapback_(true);


// try toggling knob between snapback and none by typing
$t // toggle 
$m // momentary with snapback

// try clicking on a button - mometary by desc;
// then try switching button between snapback and none by typing
$t // toggle 
$m // momentary with snapback
